function on(a){document.getElementById(a).className="on"}function off(a){document.getElementById(a).className="off"}function onoff(a){a=document.getElementById(a);switch(a.className){case "off":a.className="on";break;default:a.className="off"}return"on"==a.className}function on2(a){document.getElementById(a).setAttribute("class","on")}function off2(a){document.getElementById(a).setAttribute("class","off")}
function onoff2(a){a=document.getElementById(a);a.setAttribute("class","off"==a.getAttribute("class")?"on":"off");return"off"==a.getAttribute("class")?!1:!0}function toRad(a){return Math.PI/180*a}function toDeg(a){return 180/Math.PI*a}function round2(a,b){void 0==b&&(b=0);return Math.round(a*Math.pow(10,b))/Math.pow(10,b)}function inArray(a,b){for(var d=!1,e=b.length,c=0;c<e;c++)a==b[c]&&(d=!0,c=e);return d}
function inArrayRange(a,b,d){for(var e=!1,c=d.length,f=0;f<c;f++)d[f]>=a-b&&d[f]<=a+b&&(e=!0,f=c);return e}function Asc(a,b){return a-b}function Desc(a,b){return b-a}var isMS=!1;if(document.documentMode||/Edge/.test(navigator.userAgent))isMS=!0;function copyToClipboard(a){document.getElementById(a).select();document.execCommand("copy")};

var editor="editor",gridStrokeWidth=.1,gridStep=24,isShift=!1,isCtrl=!1,isAlt=!1,isBtnShift=!1,isBtnCtrl=!1,isBtnAlt=!1,newMol=!0,mouseIsDown=!1,coordDown=[],coordUp=[],onAtom=-1,onBond=-1,blen=24,atomRadius=7,minBondLength=10,angleStep=30,atoms=[],bonds=[],rotation=0,distance=0,distanceX=0,distanceY=0,hmol=[],hcount=0;

function showTooltip(a,b){void 0==a&&(a="");void 0==b&&(b=document.getElementById("tooltip"));b.innerHTML=a}function sBtn(a,b){var c=document.getElementById(a);switch(b){default:c.className=c.className.split(" active")[0];break;case 1:c.className=c.className.split(" active")[0]+" active"}}
function tBtn(a){a=document.getElementById(a);var b=a.className.split(" ");switch(!0){case "active"==b[1]:case "active"==b[2]:a.className=a.className.split(" active")[0];break;default:a.className=a.className.split(" active")[0]+" active"}}function checkBtn(a,b){void 0==a&&(a="btnShift");void 0==b&&(b=2);return"active"==document.getElementById(a).className.split(" ")[b]}
function aBtn(a,b){for(var c=document.getElementsByTagName("BUTTON"),g=c.length,h=document.getElementById("btnX"),f=document.getElementById("inpX"),k=document.getElementById("mode"),l=[0,1,3,4,5,6,7,8,9,10,31,33,42,43,44],e,d=0;d<g;d++)switch(e=!inArray(d,l),!0){case e&&c[d]==a:c[d].className+=" active";k.value=d;a==h?on(f.id):off(f.id);break;case e:c[d].className=c[d].className.split(" active")[0]}};

function chCla(a){void 0==a&&(a="tooltip");a=document.getElementById(a);a.className="tooltip"==a.className?"tooltip2":"tooltip"};

function copyTools(){switch(!0){case checkBtn("btnReac",1):getRxn();setRxn();break;default:getMol()}copyToClipboard("mol")};

function delSelected(){for(var c=atoms.length,b,a=c-1;0<=a;a--)switch(b=document.getElementById(atoms[a][2]),b=b.className.split(" "),!0){case "a_selected"==b[1]:case "a_selected"==b[2]:removeAtom2(atoms[a][2])}atoms.length!=c&&histAdd()}function removeAtom2(c){var b=document.getElementById(c),a=bonds.length;b=parseInt(b.id.split("a")[1]);for(--a;0<=a;a--)bonds[a][6]!=b&&bonds[a][7]!=b||removeBond2(bonds[a][3],b);renameBonds2(b);removeAtom(c)}
function removeBond2(c,b){var a=document.getElementById(c);a.parentElement.removeChild(a);a=parseInt(c.split("b")[1]);var d=bonds[a][6],e=bonds[a][7],g=bonds[a][8];atoms[d][6]=0;atoms[e][6]=0;atoms[d][8]-=g;atoms[e][8]-=g;addSymbol(atoms[d][2]);addSymbol(atoms[e][2]);bonds.splice(a,1)}
function renameBonds2(c){for(var b=bonds.length,a,d,e,g,f=0;f<b;f++)el=document.getElementById(bonds[f][3]),a=bonds[f][6],d=bonds[f][7],a>c&&a--,d>c&&d--,e="b"+f,g="Bond "+(f+1),el.id=e,el.title=g,bonds[f][3]=e,bonds[f][5]=g,bonds[f][6]=Math.min(a,d),bonds[f][7]=Math.max(a,d)}function removeAtom(c){var b=document.getElementById(c);b.parentElement.removeChild(b);b=atoms.length;for(var a=0;a<b;a++)switch(!0){case atoms[a][2]==c:atoms.splice(a,1),a=b}renameAtoms()}
function removeBond(c){var b=document.getElementById(c);b.parentElement.removeChild(b);c=parseInt(c.split("b")[1]);b=bonds[c][6];var a=bonds[c][7],d=bonds[c][8];atoms[b][6]=0;atoms[a][6]=0;atoms[b][8]-=d;atoms[a][8]-=d;addSymbol(atoms[b][2]);addSymbol(atoms[a][2]);bonds.splice(c,1);renameBonds()}
function renameAtoms(){for(var c=atoms.length,b,a,d,e=0;e<c;e++)d=document.getElementById(atoms[e][2]),n=parseInt(d.id.split("a")[1]),b="a"+e,a="Atom "+(e+1),d.id=b,document.getElementById("s"+n).id="s"+e,document.getElementById("m"+n).id="m"+e,atoms[e][2]=b,atoms[e][4]=a}function renameBonds(){for(var c=bonds.length,b,a,d=0;d<c;d++)el=document.getElementById(bonds[d][3]),b="b"+d,a="Bond "+(d+1),el.id=b,el.title=a,bonds[d][3]=b,bonds[d][5]=a}
function removeH(){for(var c=atoms.length,b,a=c-1;0<=a;a--)b=atoms[a][5],"H"==b&&removeAtom2(atoms[a][2]);0==atoms.length&&clearWorkspace();atoms.length!=c&&histAdd()};

function clearWorkspace(a){void 0==a&&(a="workspace");document.getElementById(a).innerHTML="";atoms=[];bonds=[];distanceY=distanceX=distance=rotation=0};

function selectAtoms(k){void 0==k&&(k=0);for(var m=atoms.length,c,e=0;e<m;e++)switch(c=atoms[e][2],c=document.getElementById(c),k){default:c.className=atoms[e][0]>=Math.min(coordDown[0],coordDown[0]+distanceX)&&atoms[e][0]<=Math.max(coordDown[0],coordDown[0]+distanceX)&&atoms[e][1]>=Math.min(coordDown[1],coordDown[1]+distanceY)&&atoms[e][1]<=Math.max(coordDown[1],coordDown[1]+distanceY)?c.className.split(" a_selected")[0]+" a_selected":c.className.split(" a_selected")[0];break;case 1:c.className=
c.className.split(" a_selected")[0]}}
function selectBonds(k){void 0==k&&(k=0);for(var m=bonds.length,c,e,h,f=0;f<m;f++)switch(c=bonds[f][3],c=document.getElementById(c),e=bonds[f][6],h=bonds[f][7],k){default:c.className=atoms[e][0]>=Math.min(coordDown[0],coordDown[0]+distanceX)&&atoms[e][0]<=Math.max(coordDown[0],coordDown[0]+distanceX)&&atoms[e][1]>=Math.min(coordDown[1],coordDown[1]+distanceY)&&atoms[e][1]<=Math.max(coordDown[1],coordDown[1]+distanceY)||atoms[h][0]>=Math.min(coordDown[0],coordDown[0]+distanceX)&&atoms[h][0]<=Math.max(coordDown[0],
coordDown[0]+distanceX)&&atoms[h][1]>=Math.min(coordDown[1],coordDown[1]+distanceY)&&atoms[h][1]<=Math.max(coordDown[1],coordDown[1]+distanceY)?c.className.split(" b_selected")[0]+" b_selected":c.className.split(" b_selected")[0];break;case 1:c.className=c.className.split(" b_selected")[0]}}
function selectMol(k,m){void 0==m&&(m=0);var c=bonds.length,e=[k],h=[];var f=1;do{var g=e.length;jmin=g-f;jmax=g;for(var l=jmin;l<jmax;l++)for(k=e[l],f=0;f<c;f++){var n=bonds[f][6];var p=bonds[f][7];switch(!0){case n==k&&!inArray(p,e):e.push([p]);break;case p==k&&!inArray(n,e):e.push([n])}}f=e.length;f-=g}while(0<f);for(f=0;f<c;f++)switch(n=bonds[f][6],p=bonds[f][7],!0){case inArray(n,e):case inArray(p,e):h.push([f])}c=e.length;for(f=0;f<c;f++)switch(k=e[f],g=atoms[k][2],g=document.getElementById(g),
m){default:g.className=g.className.split(" a_selected")[0]+" a_selected";break;case 1:g.className=g.className.split(" a_selected")[0]}c=h.length;for(f=0;f<c;f++)switch(b=h[f],g=bonds[b][3],g=document.getElementById(g),m){default:g.className=g.className.split(" b_selected")[0]+" b_selected";break;case 1:g.className=g.className.split(" b_selected")[0]}}function moveTool(){var k=isOnAtom2(coordDown[0],coordDown[1]);switch(!0){case -1==k:moveAll();break;case -1!=k:moveSelected(),selectMol(k,1)}}
function moveAll(){for(var k=atoms.length,m=bonds.length,c,e=0;e<k;e++)c=atoms[e][2],c=document.getElementById(c),x=round2(parseFloat(c.style.left),2)+distanceX,y=round2(parseFloat(c.style.top),2)+distanceY,c.style.left=x+"px",c.style.top=y+"px",atoms[e][0]=x,atoms[e][1]=y;for(e=0;e<m;e++)c=bonds[e][3],c=document.getElementById(c),x=round2(parseFloat(c.style.left),2)+distanceX,y=round2(parseFloat(c.style.top),2)+distanceY,c.style.left=x+"px",c.style.top=y+"px",bonds[e][0]=x,bonds[e][1]=y}
function moveSelected(){switch(!0){case isShift:case isBtnShift:rotateSel();break;default:moveSel()}}
function moveSel(){for(var k=atoms.length,m=bonds.length,c,e,h=0;h<k;h++)switch(c=atoms[h][2],c=document.getElementById(c),e=c.className.split(" "),!0){case "a_selected"==e[1]:case "a_selected"==e[2]:x=round2(parseFloat(c.style.left),2)+distanceX,y=round2(parseFloat(c.style.top),2)+distanceY,c.style.left=x+"px",c.style.top=y+"px",atoms[h][0]=x,atoms[h][1]=y}for(h=0;h<m;h++)switch(c=bonds[h][3],c=document.getElementById(c),e=c.className.split(" "),!0){case "b_selected"==e[1]:case "b_selected"==e[2]:x=
round2(parseFloat(c.style.left),2)+distanceX,y=round2(parseFloat(c.style.top),2)+distanceY,c.style.left=x+"px",c.style.top=y+"px",bonds[h][0]=x,bonds[h][1]=y}}
function rotateSel(){var k=atoms.length;if(0!=rotation)var m=5*round2(rotation/5,0);else return!1;for(var c=9999,e=0,h=9999,f=0,g=0;g<k;g++){var l=atoms[g][2];l=document.getElementById(l);var n=l.className.split(" ");switch(!0){case "a_selected"==n[1]:case "a_selected"==n[2]:x=round2(parseFloat(l.style.left),2),y=round2(parseFloat(l.style.top),2),c=c<x?c:x,e=e>x?e:x,h=h<y?h:y,f=f>y?f:y}}c=(c+e)/2;h=(h+f)/2;for(g=0;g<k;g++)switch(l=atoms[g][2],l=document.getElementById(l),n=l.className.split(" "),
!0){case "a_selected"==n[1]:case "a_selected"==n[2]:x=round2(parseFloat(l.style.left),2),y=round2(parseFloat(l.style.top),2),a=toDeg(Math.atan2(y-h,x-c)),a+=m,d=Math.sqrt((x-c)*(x-c)+(y-h)*(y-h)),x=c+d*Math.cos(toRad(a)),y=h+d*Math.sin(toRad(a)),l.style.left=x+"px",l.style.top=y+"px",atoms[g][0]=x,atoms[g][1]=y}k=getMol(1,1);setMol(k,1);histAdd();return!0}
function moveTool2(){for(var k=atoms.length,m=bonds.length,c,e=0;e<k;e++)c=atoms[e][2],c=document.getElementById(c),x=parseInt(c.style.left)+distanceX,y=parseInt(c.style.top)+distanceY,atoms[e][0]=x,atoms[e][1]=y;for(e=0;e<m;e++)c=bonds[e][3],c=document.getElementById(c),x=parseInt(c.style.left)+distanceX,y=parseInt(c.style.top)+distanceY,bonds[e][0]=x,bonds[e][1]=y;for(e=0;e<k;e++)c=atoms[e][2],c=document.getElementById(c),c.style.left=atoms[e][0]+"px",c.style.top=atoms[e][1]+"px";for(e=0;e<m;e++)c=
bonds[e][3],c=document.getElementById(c),c.style.left=bonds[e][0]+"px",c.style.top=bonds[e][1]+"px"}
function moveCenter(){var k=atoms.length,m=bonds.length,c=ws.offsetWidth/2,e=ws.offsetHeight/2,h=[];var f=[];for(var g=0;g<k;g++)h.push([atoms[g][0]]),f.push([atoms[g][1]]);h.sort(Asc);f.sort(Asc);var l=h.length;g=parseInt(h[0]);var n=parseInt(h[l-1]);h=parseInt(f[0]);f=parseInt(f[l-1]);c-=(g+n)/2;e-=(h+f)/2;for(g=0;g<k;g++)f=atoms[g][2],f=document.getElementById(f),x=parseInt(f.style.left)+c,y=parseInt(f.style.top)+e,f.style.left=x+"px",f.style.top=y+"px",atoms[g][0]=x,atoms[g][1]=y;for(g=0;g<m;g++)f=
bonds[g][3],f=document.getElementById(f),x=parseInt(f.style.left)+c,y=parseInt(f.style.top)+e,f.style.left=x+"px",f.style.top=y+"px",bonds[g][0]=x,bonds[g][1]=y};

function clearGrid(){document.getElementById("grid").innerHTML=""}
function showGrid(){var d=!1,e=document.getElementById("grid"),a=document.getElementById("workspace");switch(e.innerHTML){case "":d=!0;var b=a.offsetWidth;a=a.offsetHeight;cod='<svg width="'+b+'px" height="'+a+'px" viewBox="0 0 '+b+" "+a+'"';cod+=' preserveAspectRatio="xMinYMax slice"';cod+=' xmlns:xlink="http://www.w3.org/1999/xlink">';for(var c=0;c<=b;c+=gridStep)cod+=' <path style="stroke:black;stroke-width:'+gridStrokeWidth+';" d="M'+c+",0 V"+a+'"></path>';for(c=0;c<=a;c+=gridStep)cod+=' <path style="stroke:black;stroke-width:'+
gridStrokeWidth+';" d="M0,'+c+" H"+b+'"></path>';b-=10;a/=2;cod+='<text style="writing-mode:tb;" x="'+b+'" y="'+a+'" fill="yellow" font-size="14" text-anchor="middle">Flame JS &copy; Design H5</text>';cod+='<text style="writing-mode:tb;" x="'+b+'" y="'+(a+1)+'" fill="red" font-size="14" text-anchor="middle">Flame JS &copy; Design H5</text>';cod+="</svg>";break;default:cod=""}e.innerHTML=cod;return d};

var ed=document.getElementById(editor);initPage();
function initPage(){var h="menuTop menuTop2 menuLeft menuBottom menuBottom2 workspace grid imgArrow".split(" "),k=["tooltip","tooltip2"],m=["inpX"],n=["wsCode","mol"];ed.innerHTML=' <svg class="off" id="imgSvgId" preserveAspectRatio="xMinYMax slice">  <g id="imgSvgG">   <path id="imgSvgPath" d="M0,0 l24,24" transform="rotate(0 0 0)"></path>  </g> </svg>';for(var c=h.length,a="",b=0;b<c;b++)a=document.createElement("DIV"),a.id=h[b],ed.appendChild(a);var p=document.getElementById(h[0]),q=document.getElementById(h[1]),
t=document.getElementById(h[2]),r=document.getElementById(h[3]),u=document.getElementById(h[4]),v=document.getElementById(h[5]);document.getElementById(h[6]);a=document.getElementById(h[7]);a.className="off";a.innerHTML=' <svg preserveAspectRatio="xMinYMax slice"><path style="stroke-width:1;stroke:black;fill:transparent;" d="M1,5 h25 l-5,-3 m5,3 l-5,3"></path></svg>';var d="btnInfo btnNew btnDel btnUndo btnRedo btnCopy btnHydr btnCent btnReac btnNmol btnGrid".split(" ");c=d.length;for(b=0;b<c;b++)a=
document.createElement("BUTTON"),a.id=d[b],a.className="btn",p.appendChild(a);a=document.createElement("SPAN");a.id=k[1];a.className="tooltip";p.appendChild(a);p=document.getElementById(d[0]);h=document.getElementById(d[1]);var w=document.getElementById(d[2]),x=document.getElementById(d[3]),y=document.getElementById(d[4]),z=document.getElementById(d[5]),A=document.getElementById(d[6]),B=document.getElementById(d[7]),C=document.getElementById(d[8]),D=document.getElementById(d[9]);d=document.getElementById(d[10]);
var E=document.getElementById(k[1]),e="btnH btnC btnN btnO btnS btnF btnCl btnBr btnI btnP btnX".split(" ");c=e.length;for(b=0;b<c;b++)a=document.createElement("BUTTON"),a.id=e[b],a.className="btn",q.appendChild(a);a=document.createElement("INPUT");a.id=m[0];a.type="text";a.className="off";q.appendChild(a);q=document.getElementById(e[0]);var F=document.getElementById(e[1]),G=document.getElementById(e[2]),H=document.getElementById(e[3]),I=document.getElementById(e[4]),J=document.getElementById(e[5]),
K=document.getElementById(e[6]),L=document.getElementById(e[7]),M=document.getElementById(e[8]),N=document.getElementById(e[9]);e=document.getElementById(e[10]);m=document.getElementById(m[0]);var f="btnMove btnSel btnSingle btnDouble btnTriple btnUp btnDown btnCharge btnMapping btn31 btn32".split(" ");c=f.length;for(b=0;b<c;b++)a=document.createElement("BUTTON"),a.id=f[b],a.className="btn",t.appendChild(a);t=document.getElementById(f[0]);var O=document.getElementById(f[1]),P=document.getElementById(f[2]),
Q=document.getElementById(f[3]),R=document.getElementById(f[4]),S=document.getElementById(f[5]),T=document.getElementById(f[6]),U=document.getElementById(f[7]),V=document.getElementById(f[8]),W=document.getElementById(f[9]);f=document.getElementById(f[10]);var g="btnMode btnChain btnRing3 btnRing4 btnRing5 btnBenzene btnRing6 btnRing7 btnRing8".split(" ");c=g.length;for(b=0;b<c;b++)a=document.createElement("BUTTON"),a.id=g[b],a.className="btn",r.appendChild(a);a=document.createElement("SPAN");a.id=
k[0];a.className="tooltip";r.appendChild(a);r=document.getElementById(g[0]);var X=document.getElementById(g[1]),Y=document.getElementById(g[2]),Z=document.getElementById(g[3]),aa=document.getElementById(g[4]),ba=document.getElementById(g[5]),ca=document.getElementById(g[6]),da=document.getElementById(g[7]);g=document.getElementById(g[8]);k=document.getElementById(k[0]);var l=["btnShift","btnCtrl","btnAlt"];c=l.length;for(b=0;b<c;b++)a=document.createElement("BUTTON"),a.id=l[b],a.className="btn",u.appendChild(a);
u=document.getElementById(l[0]);c=document.getElementById(l[1]);b=document.getElementById(l[2]);a=p;a.title="Flame JS Molecular Editor\n- JavaScript version of the FlaME,\n- by Pavel Dallakian, Design H5";a.innerHTML='<svg class="btn_svg"><text x="4" y="19" style="font-size:8px;font-weight:bold;">JS</text><path style="stroke-width:.5;stroke:#8a8a8a;fill:red;" d="M7,12 l-2,-2 l-1,-2 l0,-1 l3,-3 l0,-2 l4,2 l2,3 l0,2 l-2,3 z"></path><path style="stroke-width:.5;stroke:orange;fill:orange;" d="M7,12 l-1,-2 l0,-2 l3,-3 l3,2 l0,3 l-1,1 z"></path><path style="stroke-width:.5;stroke:yellow;fill:yellow;" d="M8,12 l-1,-2 l0,-1 l1,-1 l1,-1 l1,0 l1,2 l0,1 l-1,2 z"></path></svg>';
a.onmouseover=function(){showTooltip("Flame JS &copy; Design H5")};a.onclick=function(){tBtn(this.id);chCla("tooltip")};a=h;a.title="Clear Workspace:\n- start a new structure.";a.innerHTML='<svg class="btn_svg"><path style="stroke-width:.3;stroke:black;fill:#ffffff;" d="M4,4 L13,4 L17,10 L17,20 L4,20 L4,4 M13,4 L13,10 L17,10 Z"></path></svg>';a.onmouseover=function(){showTooltip("Clear Workspace")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){clearWorkspace()};a=w;a.title=
"Delete Mode:\n- delete selected atom | bond or\n- delete previously selected atoms and bonds.";a.innerHTML='<svg class="btn_svg"><path style="stroke-linecap:round;stroke-width:1.0;stroke:red;fill:transparent;" d="M7,17 L13,5 M13,17 L7,5"></path><ellipse cx="6" cy="16" rx="1.4" ry="1.8" stroke="red" stroke-width="1.1" fill="transparent"></ellipse><ellipse cx="14" cy="16" rx="1.4" ry="1.8" stroke="red" stroke-width="1.1" fill="transparent"></ellipse><circle cx="10" cy="11" r=".3" stroke="white" stroke-width=".5" fill="white"></circle></svg>';
a.onmouseover=function(){showTooltip("Delete Mode")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){aBtn(this);delSelected()};a=x;a.title="Undo | Ctrl+Z\n- undo structure input.";a.innerHTML='<svg class="btn_svg"><path style="stroke-width:.4;stroke:black;fill:transparent;" d="M4,15 C4,15 3,8 10,7 C10,7 16,7 16,15" /><path style="stroke-width:.4;stroke:black;fill:black;" d="M4,18 L2,14 L4,15 Z"></path><path style="stroke-width:.4;stroke:black;fill:black;" d="M4,18 L6,14 L4,15 Z"></path></svg>';
a.onmouseover=function(){showTooltip("Undo")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){histUndo()};a.disabled=!0;a=y;a.title="Redo | Ctrl+Y\n- redo structure input.";a.innerHTML='<svg class="btn_svg"><path style="stroke-width:.4;stroke:black;fill:transparent;" d="M4,15 C4,15 3,8 10,7 C10,7 16,7 16,15"></path><path style="stroke-width:.4;stroke:black;fill:black;" d="M16,18 L14,14 L16,15 Z"></path><path style="stroke-width:.4;stroke:black;fill:black;" d="M16,18 L18,14 L16,15 Z"></path></svg>';
a.onmouseover=function(){showTooltip("Redo")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){histRedo()};a.disabled=!0;a=z;a.title="Copy:\n- copy MDL molfile | RXN file to the clipboard,\n- copy reagents to products if none exist or vica versa.";a.innerHTML='<svg class="btn_svg"><path style="stroke-width:.5;stroke:black;fill:transparent;" d="M3,3 H13 V8 M8,15 H3 V3"></path><path style="stroke-width:.5;stroke:black;fill:transparent;" d="M8,8 H18 V20 H8 Z"></path><path style="stroke-width:.3;stroke:black;fill:transparent;" d="M5,6 H11 M5,9 H7 M5,12 H7 M10,11 H16 M10,14 H16 M10,17 H16"></path></svg>';
a.onmouseover=function(){showTooltip("MOL|RXN 2 Clipboard")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){copyTools()};a=A;a.title="Remove Hydrogens:\n- remove all explicit hydrogens.";a.innerHTML='<svg class="btn_svg"><path style="stroke-width:.8;stroke:black;fill:transparent;" d="M3,12 H6 M8,7 V17 M14,7 V17 M8,12 H14"></path></svg>';a.onmouseover=function(){showTooltip("Remove Hydrogens")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){removeH()};
a=B;a.title="Center | Alt+C:\n- move current structure to the center.";a.innerHTML='<svg class="btn_svg"><path style="stroke-width:.5;stroke:black;fill:transparent;" d="M4,12 H16 M10,6 V18" /><circle cx="10" cy="12" r="2" stroke="black" stroke-width=".5" fill="white"></path></svg>';a.onmouseover=function(){showTooltip("Center")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){moveCenter()};a=C;a.title="Reaction Arrow | Alt+R:\n- toggle on | off reaction mode.";a.innerHTML='<svg class="btn_svg"><path style="stroke-width:.7;stroke:black;fill:transparent;" d="M5,12 H16 L13,9 L15,12 M16,12 L13,15 L15,12"></path></svg>';
a.onmouseover=function(){showTooltip("Reaction Arrow")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){tBtn(this.id);onoff2("imgArrow")};a=D;a.title="New Molecule:\n- add new molecule to the workspace.";a.innerHTML='<svg class="btn_svg"><path style="stroke-width:.4;stroke:black;fill:transparent;" d="M7,7 H16 V16 H7 Z"></path><path style="stroke-width:1.3;stroke:darkblue;fill:transparent;" d="M3,7 H11 M7,11 V3"></path></svg>';a.onmouseover=function(){showTooltip("New Molecule")};
a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){tBtn(this.id)};a=d;a.title="Grid | Alt+G\n- toggle on | off grid lines.";a.innerHTML='<svg class="btn_svg"><path style="stroke-width:.4;stroke:black;fill:transparent;" d="M7,5 V18  M13,5 V18  M3,9 H17  M3,14 H17"></path></svg>';a.onmouseover=function(){showTooltip("Grid")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){tBtn(this.id);showGrid()};a=E;a.title="Workspace messages";a.className="tooltip tooltip3";
a.innerHTML="Size: "+v.offsetWidth+" : "+v.offsetHeight+" px";a=q;a.title="H";a.className+=" h-bold";a.innerHTML="H";a.onmouseover=function(){showTooltip("Hydrogen")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){aBtn(this)};a=F;a.title="C";a.className+=" h-bold";a.innerHTML="C";a.onmouseover=function(){showTooltip("Carbon")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){aBtn(this)};a=G;a.title="N";a.className+=" h-bold h-blue";a.innerHTML="N";
a.onmouseover=function(){showTooltip("Nitrogen")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){aBtn(this)};a=H;a.title="O";a.className+=" h-bold h-red";a.innerHTML="O";a.onmouseover=function(){showTooltip("Oxygen")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){aBtn(this)};a=I;a.title="S";a.className+=" h-bold h-sulphur";a.innerHTML="S";a.onmouseover=function(){showTooltip("Sulphur")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){aBtn(this)};
a=J;a.title="F";a.className+=" h-bold h-fluorine";a.innerHTML="F";a.onmouseover=function(){showTooltip("Fluorine")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){aBtn(this)};a=K;a.title="Cl";a.className+=" h-bold h-chlorine";a.innerHTML="Cl";a.onmouseover=function(){showTooltip("Chlorine")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){aBtn(this)};a=L;a.title="Br";a.className+=" h-bold h-bromine";a.innerHTML="Br";a.onmouseover=function(){showTooltip("Bromine")};
a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){aBtn(this)};a=M;a.title="I";a.className+=" h-bold h-iodine";a.innerHTML="I";a.onmouseover=function(){showTooltip("Iodine")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){aBtn(this)};a=N;a.title="P";a.className+=" h-bold h-phosphorus";a.innerHTML="P";a.onmouseover=function(){showTooltip("Phosphorus")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){aBtn(this)};a=e;a.title="X";a.className+=
" h-bold";a.innerHTML="X";a.onmouseover=function(){showTooltip("Any Element")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){aBtn(this)};a=m;a.title="X";a.placeholder="X";a.value="X";a.className="off";a.onmouseover=function(){showTooltip("Any Element")};a.onmouseout=function(){showTooltip("Tooltip")};a.onfocus=function(){this.style.textAlign="left"};a.onblur=function(){this.style.textAlign="center"};a=t;a.title="Moving Tool:\n- move all workspace content or\n- mouse down on atom to select and move molecule.";
a.innerHTML='<svg class="btn_svg"><path class="pCla1" d="M4,12H16M10,6V18 M4,12L6,10L5,12 M4,12L6,14L5,12 M16,12L14,10L15,12 M16,12L14,14L15,12 M10,6L8,8L10,7 M10,6L12,8L10,7 M10,18L8,16L10,17 M10,18L12,16L10,17"></path></svg>';a.onmouseover=function(){showTooltip("Moving Tool")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){aBtn(this)};a=O;a.title="Selection Tool:\n- click on atom to select molecule or\n- mouse down and move to select area.";a.innerHTML='<svg class="btn_svg"><path style="stroke-width:.5;stroke:black;stroke-dasharray:1,1;fill:transparent;" d="M4,4 H16 V18 H4 Z"></path><path style="stroke-width:.8;stroke:black;fill:#f5f5f5;" d="M4,4 L10,5 L8,7 L14,12 L12,14 L7,9 L5,11 Z"></path></svg>';
a.onmouseover=function(){showTooltip("Selection Tool")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){aBtn(this)};a=P;a.title="Single Bond:\n- create single bond or\n- toggle single | double bond.";a.innerHTML='<svg class="btn_svg"><path class="pCla2" d="M3,10 H16"></path></svg>';a.onmouseover=function(){showTooltip("Single Bond")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){aBtn(this)};a=Q;a.title="Double Bond";a.innerHTML='<svg class="btn_svg"><path class="pCla2" d="M3,8 H16 M3,12 H16"></path></svg>';
a.onmouseover=function(){showTooltip("Double Bond")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){aBtn(this)};a=R;a.title="Triple Bond";a.innerHTML='<svg class="btn_svg"><path class="pCla2" d="M3,10 H16 M3,7 H16 M3,13 H16"></path></svg>';a.onmouseover=function(){showTooltip("Triple Bond")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){aBtn(this)};a=S;a.title="Single Bond Up";a.innerHTML='<svg class="btn_svg"><path style="stroke-width:.8;stroke:black;fill:black;" d="M3,10 L16,8 L16,12 Z"></path></svg>';
a.onmouseover=function(){showTooltip("Single Bond Up")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){aBtn(this)};a=T;a.title="Single Bond Down";a.innerHTML='<svg class="btn_svg"><path class="pCla2" d="M1,10 l1,0 m2,-1 l0,2 m3,-2.5 l0,3 m3,-4 l0,5 m3,-5.5 l0,6 m3,-7 l0,8"></path></svg>';a.onmouseover=function(){showTooltip("Single Bond Down")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){aBtn(this)};a=U;a.title="Charge:\n- click on atom to set a positive or negative charge.";
a.innerHTML='<svg class="btn_svg"><path class="pCla2" d="M1,10 H9 M11,10 H19 M5,6 V14"></path></svg>';a.onmouseover=function(){showTooltip("Charge")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){aBtn(this)};a=V;a.title="Mapping Tool:\n- click on atom to set | increase order number or\n- hold shift and click to decrease or\n- hold ctrl and click to reset.";a.innerHTML='<svg class="btn_svg"><path class="pCla2" d="M4,16 V7 L7,15 L10,7 V16 M15,16 V8 L13,10"></path></svg>';a.onmouseover=
function(){showTooltip("Mapping Tool")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){aBtn(this)};a=W;a.title="Reserved Button";a.innerHTML="";a.onmouseover=function(){showTooltip("Reserved Button")};a.onmouseout=function(){showTooltip("Tooltip")};a=f;a.title="Isochain";a.innerHTML='<svg class="btn_svg"><path class="pCla1" d="M1,18 L9,12 L17,18 M9,12 V3"></path></svg>';a.onmouseover=function(){showTooltip("Isochain")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=
function(){aBtn(this)};r.innerHTML='<input readonly class="num" id="mode" type="hidden" value="0">';a=X;a.title="Chain:\n- click and move mouse to set a chain.";a.innerHTML='<svg class="btn_svg"><path class="pCla1" d="M3,18 L7,5 L11,18 L15,5 L19,18"></path></svg>';a.onmouseover=function(){showTooltip("Chain")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){aBtn(this)};a=Y;a.title="Cyclopropane";a.innerHTML='<svg class="btn_svg"><path class="pCla1" d="M4,18 L11,5 L18,18 Z"></path></svg>';
a.onmouseover=function(){showTooltip("Cyclopropane")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){aBtn(this)};a=Z;a.title="Cyclobutane";a.innerHTML='<svg class="btn_svg"><path class="pCla1" d="M4,18 L4,5 L18,5 L18,18 Z"></path></svg>';a.onmouseover=function(){showTooltip("Cyclobutane")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){aBtn(this)};a=aa;a.title="Cyclopentane";a.innerHTML='<svg class="btn_svg"><path class="pCla1" d="M5,18 L2,10 L10,4 L18,10 L15,18 Z"></path></svg>';
a.onmouseover=function(){showTooltip("Cyclopentane")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){aBtn(this)};a=ba;a.title="Benzene";a.innerHTML='<svg class="btn_svg"><path class="pCla1" d="M3,16L3,7L11,3L19,7L19,16L11,20Z M5,15L5,8 M11,6L17,9 M11,17L17,14"></path></svg>';a.onmouseover=function(){showTooltip("Benzene")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){aBtn(this)};a=ca;a.title="Cyclohexane";a.innerHTML='<svg class="btn_svg"><path class="pCla1" d="M3,16 L3,7 L11,3 L19,7 L19,16 L11,20 Z"></path></svg>';
a.onmouseover=function(){showTooltip("Cyclohexane")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){aBtn(this)};a=da;a.title="Cycloheptane";a.innerHTML='<svg class="btn_svg"><path class="pCla1" d="M6,19 L1,14 L2,7 L10,3 L18,7 L19,14 L14,19 Z"></path></svg>';a.onmouseover=function(){showTooltip("Cycloheptane")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){aBtn(this)};a=g;a.title="Cyclooctane";a.innerHTML='<svg class="btn_svg"><path class="pCla1" d="M5,19 L1,14 L1,8 L5,3 L14,3 L18,8 L18,14 L14,19 Z"></path></svg>';
a.onmouseover=function(){showTooltip("Cyclooctane")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){aBtn(this)};a=k;a.title="Tooltip";a.className="tooltip";a.innerHTML="";a=u;a.title="Shift Key:\n- hold shift to add spiro ring,\n- add alternative ring on bond,\n- decrease number in mapping mode.";a.className="btn special";a.innerHTML="Shift";a.onmouseover=function(){showTooltip("Shift Key")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){tBtn(this.id)};a=c;a.title="Ctrl Key";a.className="btn special";
a.innerHTML="Ctrl";a.onmouseover=function(){showTooltip("Ctrl Key")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){tBtn(this.id)};a=b;a.title="Alt Key:\n- Alt+G grid lines,\n- Alt+R reaction mode | arrow,\n- Alt+C center.";a.className="btn special";a.innerHTML="Alt";a.onmouseover=function(){showTooltip("Alt Key")};a.onmouseout=function(){showTooltip("Tooltip")};a.onclick=function(){tBtn(this.id)};c=n.length;for(b=0;b<c;b++)a=document.createElement("TEXTAREA"),a.id=n[b],document.body.appendChild(a);
wsCode=document.getElementById(n[0]);wsCode.className="off";mol=document.getElementById(n[1]);mol.className="off"};

var ws=document.getElementById("workspace"),grid=document.getElementById("grid");

svgShapes="M0,1;M0,1 h24;M0,1 h24 M0,3 h24;M0,1 h24 M0,3 h24 M0,5 h24;M0,3 l24,-3 l0,6 z;M0,3 l3,0 m3,-1 l0,2 m3,-3 l0,4 m3,-4 l0,4 m3,-4 l0,4 m3,-5 l0,6 m3,-6 l0,6;M1,1 h24 l12,21 l21,12 h-24 l-12,-21 z;M0,1 h24 l12,-21 m-12,21 l12,21;M1,1l21,-12l21,12l21,-12l21,12l21,-12l21,12l21,-12 l21,12l21,-12l21,12 M20,-1h2m-1,0v-6l-1,1 M41,-3h4m-4,0v-1l3,-2l1,-1v-1l-1,-1h-2l-1,1 M61,-2l1,1h2l1,-1v-1l-1,-1h-2m2,0l1,-1v-1l-1,-1h-2l-1,1 M84,-3h2m-1,0v-6h-1l-2,3v1h4 M104,-2l1,1h2l1,-1v-2l-1,-1h-3v-2h4 M125,-6l1,-1h2l1,1v2l-1,1h-2l-1,-1v-4l1,-1h2l1,1 M146,-1h2m-1,0v-1l2,-4v-1h-3v1 M168,-6l-1,1v1l1,1h2l1,-1v-1l-1,-1h-2l-1,-1v-1l1,-1h2l1,1v1l-1,1 M188,-2l1,1h2l1,-1v-4l-1,-1h-2l-1,1v2l1,1h2l1,-1 M207,-3h2m-1,0v-6l-1,1 M211,-4 l1,1h2l1,-1v-4l-1,-1h-2l-1,1v4;M1,1 l24,0 l-12,21 z;M1,1 l24,0 l0,24 l-24,0 z;M1,1 l24,0 l7,23 l-19,14 l-19,-14 z;M1,1 l24,0 l12,21 l-12,21 l-24,0 l-12,-21 z M1,5 l24,0 m8,16 l-11,19 m-18,0 l-11,-19;M1,1 l24,0 l12,21 l-12,21 l-24,0 l-12,-21 z;M1,1 l24,0 l15,19 l-6,23 l-22,10 l-22,-10 l-6,-23 z;M1,1 h24 l17,17 v24 l-17,17 h-24 l-17,-17 v-24 z;M1,1 h24 l21,-12 v24 l-21,-12;M1,1 h24 l17,-17 l17,17 l-17,17 l-17,-17;M1,1 h24 l14,-19 l21,7.8 v23 l-21,7.8 l-14,-19;M1,1 h24 l12,-21 h24 l12,21 l-12,21 h-24 l-12,-21 M37,-17 h24 M70,0 l-12,21 M28,0 l12,21;M1,1 h24 l12,-21 h24 l12,21 l-12,21 h-24 l-12,-21;M1,1 h24 l10.4,-21.6 l23.4,-5.1 l18.7,15 M25,1 l10.4,21.6 l23.4,5.1 l18.7,-15 v-24;M1,1 h24 l9.2,-22.2 l22.3,-9 l22.3,9 l9.2,22.2 M25,1 l9.2,22.2 l22.3,9 l22.3,-9 l9.2,-22.2;M-7,-7 h14 v14 h-14 z".split(";");
function moveSvg(f,g,e,b,a){void 0==e&&(e=0);void 0==b&&(b=0);void 0==a&&(a="imgSvgId");a=document.getElementById(a);var c=document.getElementById("imgSvgPath");c.style.stroke="blue";a.style.border="none";var d=document.getElementById("mode").value;isNewMolecule();switch(d){default:c.setAttribute("d",svgShapes[0]);a.style.width="2px";a.style.height="2px";a.setAttribute("viewBox","0 0 2 2");a.style.transformOrigin="0px 1px";d=b=0;break;case "22":b=Math.max(ws.offsetWidth,ws.offsetHeight);c.setAttribute("d",
svgShapes[0]);c.style.fill="transparent";b=isMS?"M1,1 h"+b/4:"M1,1 h"+b;c.setAttribute("d",b);a.style.height="3px";a.style.width=distance+"px";a.setAttribute("viewBox","0 0 "+distance+" 2");a.style.transformOrigin="1px 1px";d=b=-1;break;case "23":c.style.fill="#fafafa";c.style.stroke="#fafafa";selW=Math.abs(distanceX);selH=Math.abs(distanceY);a.style.width=selW+"px";a.style.height=selH+"px";vxMin=Math.min(distanceX,0);vxMax=Math.max(distanceX,0);vyMin=Math.min(distanceY,0);vyMax=Math.max(distanceY,
0);a.setAttribute("viewBox",vxMin+" "+vyMin+" "+selW+" "+selH);a.style.transformOrigin="0px 0px";d=b=0;0<=distanceX&&0<=distanceY&&(d=b=e=0);0>distanceX&&0>distanceY&&(e=0,b=vxMin,d=vyMin);0<=distanceX&&0>distanceY&&(b=e=0,d=vyMin);0>distanceX&&0<=distanceY&&(e=0,b=vxMin,d=0);c.setAttribute("d","m"+vxMin+","+vyMin+" h"+selW+" v"+selH+" h-"+selW+" z");break;case "24":c.setAttribute("d",svgShapes[1]);a.style.width="24px";a.style.height="2px";a.setAttribute("viewBox","0 0 24 2");a.style.transformOrigin=
"0px 1px";d=b=0;break;case "25":c.setAttribute("d",svgShapes[2]);a.style.width="24px";a.style.height="4px";a.setAttribute("viewBox","0 0 24 4");a.style.transformOrigin="0px 2px";d=b=0;break;case "26":c.setAttribute("d",svgShapes[3]);a.style.width="24px";a.style.height="6px";a.setAttribute("viewBox","0 0 24 6");a.style.transformOrigin="0px 3px";d=b=0;break;case "27":c.setAttribute("d",svgShapes[4]);c.style.fill="blue";a.style.width="24px";a.style.height="7px";a.setAttribute("viewBox","0 0 24 7");a.style.transformOrigin=
"0px 3px";d=b=0;break;case "28":c.setAttribute("d",svgShapes[5]);a.style.width="24px";a.style.height="7px";a.setAttribute("viewBox","0 0 24 7");a.style.transformOrigin="0px 3px";d=b=0;break;case "31":c.setAttribute("d",svgShapes[6]);c.style.fill="transparent";a.style.width="57px";a.style.height="34px";a.setAttribute("viewBox","0 0 58 35");a.style.transformOrigin="0px 1px";d=b=0;break;case "32_":c.style.fill="transparent";c.setAttribute("d",svgShapes[7]);a.style.width="46px";a.style.height="40px";
a.setAttribute("viewBox","0 -46 44 50");a.style.transformOrigin="2px 39px";b=-1;d=-37;break;case "32":c.style.fill="transparent";c.setAttribute("d",svgShapes[7]);a.style.width="40px";a.style.height="44px";a.setAttribute("viewBox","0 -28 38 50");a.style.transformOrigin="0px 22px";b=0;d=-21;break;case "342":c.style.fill="transparent";c.setAttribute("d","M2,2 l24,0 l12,21");a.style.width="42px";a.style.height="24px";a.setAttribute("viewBox","0 0 42 24");a.style.transformOrigin="2px 2px";d=b=0;break;
case "34":c.style.fill="transparent";c.setAttribute("d",svgShapes[8]);a.style.height="12px";a.style.width=distance+"px";a.setAttribute("viewBox","0 -13 "+distance+" 14");a.style.transformOrigin="2px 12px";b=-1;d=-11;break;case "35":switch(!0){case 0==b:case 1==b:case 2<=b&&isShift:case 2<=b&&isBtnShift:c.setAttribute("d",svgShapes[9]);c.style.fill="transparent";a.style.width="25px";a.style.height="25px";a.setAttribute("viewBox","0 0 25 25");a.style.transformOrigin="1px 1px";d=b=0;break;default:c.setAttribute("d",
svgShapes[16]),c.style.fill="transparent",a.style.width="46px",a.style.height="25px",a.setAttribute("viewBox","0 -27 50 42"),a.style.transformOrigin="1px 12px",b=0,d=-12}break;case "36":switch(!0){case 0==b:case 1==b:case 2<=b&&isShift:case 2<=b&&isBtnShift:c.setAttribute("d",svgShapes[10]);c.style.fill="transparent";a.style.width="25px";a.style.height="25px";a.setAttribute("viewBox","0 0 26 26");a.style.transformOrigin="1px 1px";d=b=0;break;default:c.setAttribute("d",svgShapes[17]),c.style.fill=
"transparent",a.style.width="58px",a.style.height="34px",a.setAttribute("viewBox","0 -24 60 43"),a.style.transformOrigin="1px 16px",b=0,d=-15}break;case "37":switch(!0){case 0==b:case 1==b:case 2<=b&&isShift:case 2<=b&&isBtnShift:c.setAttribute("d",svgShapes[11]);c.style.fill="transparent";a.style.width="41px";a.style.height="41px";a.setAttribute("viewBox","-7 0 41 41");a.style.transformOrigin="8px 1px";b=-7;d=0;break;default:c.setAttribute("d",svgShapes[18]),c.style.fill="transparent",a.style.width=
"60px",a.style.height="41px",a.setAttribute("viewBox","0 -24 62 47"),a.style.transformOrigin="1px 20px",b=0,d=-18}break;case "38":switch(!0){case 0==b:case 1==b:case 2<=b&&isShift:case 2<=b&&isBtnShift:c.setAttribute("d",svgShapes[12]);c.style.fill="transparent";a.style.width="47px";a.style.height="45px";a.setAttribute("viewBox","-11 0 48 46");a.style.transformOrigin="11px 1px";b=-11;d=0;break;default:c.setAttribute("d",svgShapes[19]),c.style.fill="transparent",a.style.width="72px",a.style.height=
"43px",a.setAttribute("viewBox","0 -25 74 48"),a.style.transformOrigin="1px 22px",b=0,d=-20}break;case "39":switch(!0){case 0==b:case 1==b:case 2<=b&&isShift:case 2<=b&&isBtnShift:c.setAttribute("d",svgShapes[13]);c.style.fill="transparent";a.style.width="47px";a.style.height="45px";a.setAttribute("viewBox","-11 0 48 46");a.style.transformOrigin="11px 1px";b=-11;d=0;break;default:c.setAttribute("d",svgShapes[20]),c.style.fill="transparent",a.style.width="72px",a.style.height="43px",a.setAttribute("viewBox",
"0 -25 74 48"),a.style.transformOrigin="1px 22px",b=0,d=-20}break;case "40":switch(!0){case 0==b:case 1==b:case 2<=b&&isShift:case 2<=b&&isBtnShift:c.setAttribute("d",svgShapes[14]);c.style.fill="transparent";a.style.width="57px";a.style.height="54px";a.setAttribute("viewBox","-17 0 58 55");a.style.transformOrigin="18px 1px";b=-18;d=0;break;default:c.setAttribute("d",svgShapes[21]),c.style.fill="transparent",a.style.width="80px",a.style.height="55px",a.setAttribute("viewBox","0 -28 80 56"),a.style.transformOrigin=
"1px 28px",b=0,d=-26}break;case "41":switch(!0){case 0==b:case 1==b:case 2<=b&&isShift:case 2<=b&&isBtnShift:c.setAttribute("d",svgShapes[15]);c.style.fill="transparent";a.style.width="60px";a.style.height="60px";a.setAttribute("viewBox","-17 0 61 61");a.style.transformOrigin="18px 1px";b=-18;d=0;break;default:c.setAttribute("d",svgShapes[22]),c.style.fill="transparent",a.style.width="89px",a.style.height="63px",a.setAttribute("viewBox","0 -30 89 63"),a.style.transformOrigin="1px 31px",b=0,d=-29}}isMS?
(e=" rotate("+e+" 0 0)",document.getElementById("imgSvgG").setAttribute("transform",e),a.style.left=f+b+"px",a.style.top=g+d+"px"):a.setAttribute("transform","translate("+(f+b)+","+(g+d)+") rotate("+e+")")};

function isNewMolecule(){document.getElementById("btnMol");var c=!1;switch(!0){case ""==ws.innerHTML:c=!0;break;case "active"==btnNmol.className.split(" ")[1]:c=!0}return c}function isNewBond(c,d){for(var b=!0,e=bonds.length,a=0;a<e;a++)switch(!0){case bonds[a][6]==c&&bonds[a][7]==d:case bonds[a][6]==d&&bonds[a][7]==c:b=!1,a=e}return b}
function isOnAtom(){for(var c=-1,d=atoms.length,b=0;b<d;b++)switch(!0){case Math.abs(atoms[b][0]-coordDown[0])<=atomRadius&&Math.abs(atoms[b][1]-coordDown[1])<=atomRadius:c=b,b=d}return c}function isOnAtom2(c,d){for(var b=-1,e=atoms.length,a=0;a<e;a++)switch(!0){case Math.abs(atoms[a][0]-c)<=atomRadius&&Math.abs(atoms[a][1]-d)<=atomRadius:b=a,a=e}return b};

window.onresize=function(){showTooltip("Resized","tooltip2");clearGrid();sBtn("btnGrid",0);moveCenter()};
window.onkeydown=function(a){89==a.keyCode&&a.ctrlKey&&document.getElementById("btnRedo").click();90==a.keyCode&&a.ctrlKey&&document.getElementById("btnUndo").click();67==a.keyCode&&a.altKey&&document.getElementById("btnCent").click();82==a.keyCode&&a.altKey&&document.getElementById("btnReac").click();71==a.keyCode&&a.altKey&&document.getElementById("btnGrid").click();switch(a.keyCode){case 16:isShift=!0;sBtn("btnShift",1);break;case 17:isCtrl=!0;sBtn("btnCtrl",1);break;case 18:isAlt=!0,sBtn("btnAlt",
1)}};window.onkeyup=function(a){switch(a.keyCode){case 16:isShift=!1;sBtn("btnShift",0);break;case 17:isCtrl=!1;sBtn("btnCtrl",0);break;case 18:isAlt=!1,sBtn("btnAlt",0)}};

function mouseMoveHandler(a){var b=document.getElementById("mode").value;isBtnShift=checkBtn();var d=ed.offsetTop+ed.clientTop,c=ws.offsetLeft+ws.clientLeft,g=ws.offsetTop+ws.clientTop,e=a.pageX,f=a.pageY;e=e-c-(ed.offsetLeft+ed.clientLeft);f=f-g-d;g=ws.offsetWidth-10;var h=ws.offsetHeight-10,k=isNewMolecule();d=isOnAtom2(e,f);var l=isOnAtom2(coordDown[0],coordDown[1]);c=0;if(void 0==onBond||onBond>=bonds.length)onBond=-1;switch(!0){case -1!=onBond&&"32"==b:off2("imgSvgId");break;case k:on2("imgSvgId");
break;case !k:switch(!0){default:off2("imgSvgId");break;case -1!=d:case -1!=onBond:case mouseIsDown:on2("imgSvgId")}}switch(!0){case !mouseIsDown&&-1!=onBond:c=atoms[bonds[onBond][6]][0];g=atoms[bonds[onBond][6]][1];x2=atoms[bonds[onBond][7]][0];y2=atoms[bonds[onBond][7]][1];h=toDeg(Math.atan2(y2-g,x2-c));xfix=a.clientX+(x2-c)/2;yfix=a.clientY+(y2-g)/2;if(inArray(b,"35 36 37 38 39 40 41".split(" ")))switch(!0){case isShift:case isBtnShift:switch(b){case "35":n=3;break;case "36":n=4;break;case "37":n=
5;break;case "38":case "39":n=6;break;case "40":n=7;break;case "41":n=8}da=360/n;break;default:da=-180}else da=-90,xfix=a.clientX,yfix=a.clientY;moveSvg(xfix,yfix,h+da);da=rotation=0;break;case !mouseIsDown&&-1!=d:b=nextAngle(d);rotation=da=b[0];c=b[1];xfix=a.clientX;yfix=a.clientY;distance=0;moveSvg(xfix,yfix,da,c);break;case !mouseIsDown&&k:switch(b){case "24":da=30;break;case "25":da=30;break;case "26":da=30;break;case "27":da=30;break;case "28":da=30;break;case "32":da=-30;break;case "35":n=3;
da=180/n;break;case "36":n=4;da=0;break;case "37":n=5;da=180/n;break;case "38":case "39":n=6;da=180/n;break;case "40":n=7;da=180/n;break;case "41":n=8;da=0;break;default:da=0}xfix=a.clientX;yfix=a.clientY;distance=0;moveSvg(xfix,yfix,da,0);break;case !mouseIsDown&&10<e&&e<g&&10<f&&f<h:xfix=a.clientX;yfix=a.clientY;distance=0;moveSvg(xfix,yfix,da,c);break;case mouseIsDown&&k:switch(b){case "23":break;case "35":n=3;da=180/n;break;case "36":n=4;da=0;break;case "37":n=5;da=180/n;break;case "38":case "39":n=
6;da=180/n;break;case "40":n=7;da=180/n;break;case "41":n=8;da=180/n;break;default:da=0}b=a.clientX-parseInt(xfix);a=a.clientY-parseInt(yfix);distance=Math.sqrt(Math.pow(b,2)+Math.pow(a,2));distanceX=b;distanceY=a;rotationRad=Math.atan2(a,b);rotation=toDeg(rotationRad);moveSvg(xfix,yfix,rotation+da,0);break;case mouseIsDown&&10<e&&e<g&&10<f&&f<h:b=nextAngle(l);c=b[1];-1!=d&&(rotation=da=0);b=a.clientX-parseInt(xfix);a=a.clientY-parseInt(yfix);distance=Math.sqrt(Math.pow(b,2)+Math.pow(a,2));distanceX=
b;distanceY=a;rotationRad=Math.atan2(a,b);rotation=toDeg(rotationRad);moveSvg(xfix,yfix,rotation+da,c);break;default:off2("imgSvgId")}showTooltip("x:"+e.toFixed(0)+" y:"+f.toFixed(0)+" r:"+(parseInt(rotation)||0)+"&deg;"+(-1!=d?" atom "+(d+1):"")+(-1!=onBond?" bond "+(onBond+1):"")+(mouseIsDown?" "+coordDown:""),tooltip2)};

function mouseDownHandler(a){var d=document.getElementById("mode").value;mouseIsDown=!0;var b=ed.offsetTop,e=ws.offsetTop,c=a.pageX;a=a.pageY;c=c-ws.offsetLeft-ed.offsetLeft;a=a-e-b;b=isOnAtom2(c,a);switch(!0){case 22==d&&-1!=b:selectMol(b)}coordDown[0]=c;coordDown[1]=a;return coordDown};

function mouseUpHandler(g){var d=document.getElementById("mode").value,a=ed.offsetTop,e=ws.offsetTop,c=g.pageX;g=g.pageY;c=c-ws.offsetLeft-ed.offsetLeft;g=g-e-a;isBtnShift=checkBtn();isBtnCtrl=checkBtn("btnCtrl");isBtnAlt=checkBtn("btnAlt");var b=isNewMolecule();a=isOnAtom();void 0==a&&(a=-1);mouseIsDown=!1;-1!=a?(astat=nextAngle(a),nb=astat[1]):nb=0;var h=isOnAtom2(c,g);e=atoms.length;var f=bonds.length;switch(d){case "2":switch(!0){case -1!=a:removeAtom2(atoms[a][2]),histAdd()}break;case "11":d=
"H";switch(!0){case b:b="a"+e;addAtom("atom H",b,"Atom "+(e+1),2E3+e,c,g,0,0,d);addSymbol(b);histAdd();break;case -1!=a:b="a"+a,el=document.getElementById(b),el.className="atom "+d,c=atoms[a][5],d!=c&&(atoms[a][6]=0),atoms[a][5]=d,addSymbol(b),histAdd()}break;case "12":d="C";switch(!0){case b:b="a"+e;addAtom("atom C",b,"Atom "+(e+1),2E3+e,c,g,0,0,d);addSymbol(b);histAdd();break;case -1!=a:b="a"+a,el=document.getElementById(b),el.className="atom "+d,c=atoms[a][5],d!=c&&(atoms[a][6]=0),atoms[a][5]=
d,addSymbol(b),histAdd()}break;case "13":d="N";switch(!0){case b:b="a"+e;addAtom("atom N",b,"Atom "+(e+1),2E3+e,c,g,0,0,d);addSymbol(b);histAdd();break;case -1!=a:b="a"+a,el=document.getElementById(b),el.className="atom "+d,c=atoms[a][5],d!=c&&(atoms[a][6]=0),atoms[a][5]=d,addSymbol(b),histAdd()}break;case "14":d="O";switch(!0){case b:b="a"+e;addAtom("atom O",b,"Atom "+(e+1),2E3+e,c,g,0,0,d);addSymbol(b);histAdd();break;case -1!=a:b="a"+a,el=document.getElementById(b),el.className="atom "+d,c=atoms[a][5],
d!=c&&(atoms[a][6]=0),atoms[a][5]=d,addSymbol(b),histAdd()}break;case "15":d="S";switch(!0){case b:b="a"+e;addAtom("atom S",b,"Atom "+(e+1),2E3+e,c,g,0,0,d);addSymbol(b);histAdd();break;case -1!=a:b="a"+a,el=document.getElementById(b),el.className="atom "+d,c=atoms[a][5],d!=c&&(atoms[a][6]=0),atoms[a][5]=d,addSymbol(b),histAdd()}break;case "16":d="F";switch(!0){case b:b="a"+e;addAtom("atom F",b,"Atom "+(e+1),2E3+e,c,g,0,0,d);addSymbol(b);histAdd();break;case -1!=a:b="a"+a,el=document.getElementById(b),
el.className="atom "+d,c=atoms[a][5],d!=c&&(atoms[a][6]=0),atoms[a][5]=d,addSymbol(b),histAdd()}break;case "17":d="Cl";switch(!0){case b:b="a"+e;addAtom("atom Cl",b,"Atom "+(e+1),2E3+e,c,g,0,0,d);addSymbol(b);histAdd();break;case -1!=a:b="a"+a,el=document.getElementById(b),el.className="atom "+d,c=atoms[a][5],d!=c&&(atoms[a][6]=0),atoms[a][5]=d,addSymbol(b),histAdd()}break;case "18":d="Br";switch(!0){case b:b="a"+e;addAtom("atom Br",b,"Atom "+(e+1),2E3+e,c,g,0,0,d);addSymbol(b);histAdd();break;case -1!=
a:b="a"+a,el=document.getElementById(b),el.className="atom "+d,c=atoms[a][5],d!=c&&(atoms[a][6]=0),atoms[a][5]=d,addSymbol(b),histAdd()}break;case "19":d="I";switch(!0){case b:b="a"+e;addAtom("atom I",b,"Atom "+(e+1),2E3+e,c,g,0,0,d);addSymbol(b);histAdd();break;case -1!=a:b="a"+a,el=document.getElementById(b),el.className="atom "+d,c=atoms[a][5],d!=c&&(atoms[a][6]=0),atoms[a][5]=d,addSymbol(b),histAdd()}break;case "20":d="P";switch(!0){case b:b="a"+e;addAtom("atom P",b,"Atom "+(e+1),2E3+e,c,g,0,
0,d);addSymbol(b);histAdd();break;case -1!=a:b="a"+a,el=document.getElementById(b),el.className="atom "+d,c=atoms[a][5],d!=c&&(atoms[a][6]=0),atoms[a][5]=d,addSymbol(b),histAdd()}break;case "21":f=document.getElementById("inpX").value;d=f=f.trim();switch(!0){case "H"==f:case "C"==f:case "N"==f:case "O"==f:case "S"==f:case "F"==f:case "Cl"==f:case "Br"==f:case "I"==f:case "P"==f:alert("Use a predefined button "+f+" !");break;case ""==f:alert("Input an element!");break;case b:b="a"+e;addAtom("atom X",
b,"Atom "+(e+1),2E3+e,c,g,0,0,d);addSymbol(b);histAdd();break;case -1!=a:b="a"+a,el=document.getElementById(b),el.className="atom X",c=atoms[a][5],d!=c&&(atoms[a][6]=0),atoms[a][5]=d,addSymbol(b),histAdd()}break;case "22":moveTool();break;case "23":switch(!0){case -1!=a:selectMol(a);break;default:selectAtoms(),selectBonds()}break;case "24":case "25":case "26":case "27":case "28":switch(d){default:cla="bond singleBond";break;case "25":cla="bond doubleBond";break;case "26":cla="bond tripleBond";break;
case "27":cla="bond upBond";break;case "28":cla="bond downBond"}switch(!0){case b&&Math.abs(c-coordDown[0])<=atomRadius&&Math.abs(g-coordDown[1])<=atomRadius:switch(d){case "24":angle=30;break;case "25":angle=30;break;case "26":angle=30;break;case "27":angle=30;break;case "28":angle=30;break;default:angle=0}angleRad=toRad(angle);ax=c;ay=g;dx=blen*Math.cos(angleRad);dy=blen*Math.sin(angleRad);addAtom("atom C","a"+e,"Atom "+(e+1),2E3+e,ax,ay);addAtom("atom C","a"+(e+1),"Atom "+(e+2),2E3+(e+1),ax+dx,
ay+dy);addBond(cla,"b"+f,"Bond "+(f+1),1E3+f,ax,ay,toDeg(angleRad),0,0,e,e+1);histAdd();break;case b&&(Math.abs(c-coordDown[0])>minBondLength||Math.abs(g-coordDown[1])>minBondLength):ax=coordDown[0];ay=coordDown[1];angle=toDeg(Math.atan2(g-ay,c-ax));angle=round2(angle/angleStep,0)*angleStep;dx=blen*Math.cos(toRad(angle));dy=blen*Math.sin(toRad(angle));addAtom("atom C","a"+e,"Atom "+(e+1),2E3+e,ax,ay);addAtom("atom C","a"+(e+1),"Atom "+(e+2),2E3+(e+1),ax+dx,ay+dy);addBond(cla,"b"+f,"Bond "+(f+1),1E3+
f,ax,ay,angle,0,0,e,e+1);histAdd();break;case -1!=a&&-1!=h&&(Math.abs(atoms[h][0]-atoms[a][0])>minBondLength||Math.abs(atoms[h][1]-atoms[a][1])>minBondLength):ax=atoms[a][0];ay=atoms[a][1];c=atoms[h][0];g=atoms[h][1];rlen=Math.sqrt(Math.pow(c-ax,2)+Math.pow(g-ay,2));angleRad=Math.atan2(g-ay,c-ax);dx=rlen*Math.cos(angleRad);dy=rlen*Math.sin(angleRad);addBond(cla,"b"+f,"Bond "+(f+1),1E3+f,ax,ay,toDeg(angleRad),rlen,0,a,h);histAdd();break;case -1!=a&&(Math.abs(c-atoms[a][0])>minBondLength||Math.abs(g-
atoms[a][1])>minBondLength):ax=atoms[a][0];ay=atoms[a][1];angle=toDeg(Math.atan2(g-ay,c-ax));angle=round2(angle/angleStep,0)*angleStep;dx=blen*Math.cos(toRad(angle));dy=blen*Math.sin(toRad(angle));h=isOnAtom2(ax+dx,ay+dy);-1==h&&(addAtom("atom C","a"+e,"Atom "+e,2E3+e,ax+dx,ay+dy),addBond(cla,"b"+f,"Bond "+(f+1),1E3+f,ax,ay,angle,0,0,a,e),histAdd());break;case -1!=a&&Math.abs(c-atoms[a][0])<=atomRadius&&Math.abs(g-atoms[a][1])<=atomRadius:ax=atoms[a][0],ay=atoms[a][1],angle=rotation,angleRad=toRad(angle),
dx=blen*Math.cos(angleRad),dy=blen*Math.sin(angleRad),c=isOnAtom2(ax+dx,ay+dy),-1!=c?(angleRad=Math.atan2(atoms[c][1]-ay,atoms[c][0]-ax),addBond(cla,"b"+f,"Bond "+(f+1),1E3+f,ax,ay,toDeg(angleRad),0,0,a,c)):(addAtom("atom C","a"+e,"Atom "+(e+1),2E3+e,ax+dx,ay+dy),addBond(cla,"b"+f,"Bond "+(f+1),1E3+f,ax,ay,toDeg(angleRad),0,0,a,e)),histAdd()}break;case "29":if(-1!=a){d=atoms[a][5];c=parseInt(atoms[a][6]);switch(d){case "H":break;case "N":case "P":switch(c){case 0:atoms[a][6]=1;break;case 1:atoms[a][6]=
-1;break;case -1:atoms[a][6]=0}break;default:switch(c){case 0:atoms[a][6]=-1;break;case -1:atoms[a][6]=1;break;case 1:atoms[a][6]=0}break;case "F":case "Cl":case "Br":case "I":switch(c){case 0:atoms[a][6]=-1;break;case -1:atoms[a][6]=0}}addSymbol("a"+a);histAdd()}break;case "30":if(-1!=a){c=atoms[a][7];b=atoms[a][2];switch(!0){case isShift:case isBtnShift:c=0<c?c-1:c;break;case isCtrl:case isBtnCtrl:c=0;break;default:switch(!0){case 0==c:c=lastNumber(a)}c++}atoms[a][7]=c;addNumber(b,c);histAdd()}break;
case "31":ax=coordDown[0];ay=coordDown[1];angle=b?round2(rotation/angleStep,0)*angleStep:rotation;a=[];a.push([0,0],[24,0],[36,21],[57,33],[33,33],[21,12]);addRing3(ax,ay,a,angle);histAdd();break;case "32":switch(!0){case b&&Math.abs(c-coordDown[0])<=atomRadius&&Math.abs(g-coordDown[1])<=atomRadius:ax=coordDown[0];ay=coordDown[1];angle=-30;addIsochain(ax,ay,2,angle);histAdd();break;case b:ax=coordDown[0];ay=coordDown[1];angle=round2(rotation/angleStep,0)*angleStep;addIsochain(ax,ay,2,angle);histAdd();
break;case -1!=a&&Math.abs(c-atoms[a][0])<=atomRadius&&Math.abs(g-atoms[a][1])<=atomRadius:ax=atoms[a][0];ay=atoms[a][1];angle=rotation;addIsochain(ax,ay,2,angle);histAdd();break;case -1!=a:ax=atoms[a][0],ay=atoms[a][1],angle=round2(rotation/angleStep,0)*angleStep,addIsochain(ax,ay,2,angle),histAdd()}break;case "34":switch(!0){case b:ax=coordDown[0];ay=coordDown[1];break;case -1!=a:ax=atoms[a][0],ay=atoms[a][1]}switch(!0){case b:case -1!=a:angle=round2(rotation/angleStep,0)*angleStep,n=Math.floor(distance/
21),n=10<n?10:n,0<n&&(addChain(ax,ay,n,angle),histAdd())}break;case "35":case "36":case "37":case "39":case "40":case "41":switch(d){case "35":n=3;da=180/n;break;case "36":n=4;da=0;break;case "37":n=5;da=180/n;break;case "39":n=6;da=180/n;break;case "40":n=7;da=180/n;break;case "41":n=8,da=0}ax=coordDown[0];ay=coordDown[1];angle=rotation;switch(!0){case b:Math.abs(c-coordDown[0])<=atomRadius&&Math.abs(g-coordDown[1])<=atomRadius&&(rotation=0);da=180/n;angle=round2(rotation/da,0)*da;da=inArray(n,[4,
8])?0:da;addRing2(ax,ay,n,angle+da);histAdd();break;case !b&&-1!=a&&0==nb:case 1==nb:case 2<=nb&&isShift:case 2<=nb&&isBtnShift:da=0;addRing2(ax,ay,n,angle+da);histAdd();break;case 2<=nb:da=0,addRing21(ax,ay,n,angle+da),histAdd()}break;case "37_":n=5;ax=coordDown[0];ay=coordDown[1];angle=rotation;b?(da=180/n,angle=round2(rotation/da,0)*da):da=0;addRing2(ax,ay,n,angle+da);break;case "38":switch(n=6,da=180/n,ax=coordDown[0],ay=coordDown[1],angle=rotation,!0){case b:Math.abs(c-coordDown[0])<=atomRadius&&
Math.abs(g-coordDown[1])<=atomRadius&&(rotation=0);da=180/n;angle=round2(rotation/da,0)*da;addBenzene2(ax,ay,n,angle+da);histAdd();break;case !b&&-1!=a&&0==nb:case 1==nb:case 2<=nb&&isShift:case 2<=nb&&isBtnShift:da=0;addBenzene2(ax,ay,n,angle+da);histAdd();break;case 2<=nb:da=0,addBenzene21(ax,ay,n,angle+da),histAdd()}}rotation=distanceY=distanceX=distance=0};

function mouseWheelHandler(a){var b=document.getElementById("editor");showTooltip("Wheel: "+(a.pageX-ws.offsetLeft-b.offsetLeft)+" : "+(a.pageY-ws.offsetTop-b.offsetTop),tooltip2)};

function mouseOverAtom(){var a=document.getElementById("workspace");"2"==document.getElementById("mode").value&&(this.style.background="#ffcccc",this.style.boxShadow="0px 0px 0px 1px #ff0000");a.removeEventListener("mouseup",mouseUpHandler)}function mouseOutAtom(){var a=document.getElementById("workspace");"2"==document.getElementById("mode").value&&(this.style.background="",this.style.boxShadow="");a.addEventListener("mouseup",mouseUpHandler,!1)}
function mouseDownAtom(){var a=document.getElementById("workspace");mouseIsDown=!0;a.addEventListener("mouseup",mouseUpHandler,!1)}function mouseUpAtom(){document.getElementById("workspace").addEventListener("mouseup",mouseUpHandler,!1)};

function mouseOverBond(){var a=document.getElementById("workspace"),b=document.getElementById("mode").value;"2"==b&&(this.style.background="#ffcccc",this.style.boxShadow="0px 0px 0px 1px #ff0000");inArray(b,["23"])||(a.removeEventListener("mouseup",mouseUpHandler),onBond=parseInt(this.id.split("b")[1]))}
function mouseOutBond(){var a=document.getElementById("workspace"),b=document.getElementById("mode").value;"2"==b&&(this.style.background="",this.style.boxShadow="");inArray(b,["23"])||(a.addEventListener("mouseup",mouseUpHandler,!1),onBond=-1)}
function mouseUpBond(){mouseIsDown=!1;var a=document.getElementById("mode").value;switch(a){case "2":removeBond(this.id);histAdd();break;case "24":switch(this.className){case "bond singleBond":this.className="bond doubleBond";addBond2(this,2);break;default:this.className="bond singleBond",addBond2(this,1)}changeBondType(this.id,this.className);histAdd();break;case "25":switch(this.className){case "bond doubleBond":this.className="bond singleBond";break;default:this.className="bond doubleBond"}changeBondType(this.id,
this.className);addBond2(this,2);histAdd();break;case "26":this.className="bond tripleBond";changeBondType(this.id,this.className);addBond2(this,3);histAdd();break;case "27":this.className="bond upBond";changeBondType(this.id,this.className);addStereoBond(this,0);histAdd();break;case "28":this.className="bond downBond";changeBondType(this.id,this.className);addStereoBond(this,1);histAdd();break;case "31":x2=atoms[bonds[onBond][6]][0];y2=atoms[bonds[onBond][6]][1];x1=atoms[bonds[onBond][7]][0];y1=
atoms[bonds[onBond][7]][1];angle=toDeg(Math.atan2(y2-y1,x2-x1));a=[];a.push([0,0],[24,0],[36,21],[57,33],[33,33],[21,12]);addRing3(x1,y1,a,angle);histAdd();break;case "35":case "36":case "37":case "38":case "39":case "40":case "41":switch(a){case "35":n=3;break;case "36":n=4;break;case "37":n=5;break;case "38":n=6;break;case "39":n=6;break;case "40":n=7;break;case "41":n=8}x1=atoms[bonds[onBond][6]][0];y1=atoms[bonds[onBond][6]][1];x2=atoms[bonds[onBond][7]][0];y2=atoms[bonds[onBond][7]][1];angle=
toDeg(Math.atan2(y2-y1,x2-x1));da=isShift||isBtnShift?360/n:-180;switch(a){case "38":addBenzene2(x2,y2,n,angle+da);histAdd();break;default:addRing2(x2,y2,n,angle+da),histAdd()}}};

var ws = document.getElementById("workspace");
ws && (ws.addEventListener("mousemove", mouseMoveHandler, !1), ws.addEventListener("mousedown", mouseDownHandler, !1), ws.addEventListener("mouseup", mouseUpHandler, !1), ws.addEventListener("wheel", mouseWheelHandler, !1));

function addAtom(a,f,b,h,e,g,l,d,c,m,k,n){void 0==a&&(a="atom C");void 0==b&&(b="Atom");void 0==h&&(h=2E3);void 0==c&&(c="C");void 0==m&&(m=0);void 0==k&&(k=0);void 0==n&&(n=0);l=f.split("a")[1];l='<span id="s'+l+'">'+c+"</span>"+('<span id="m'+l+'" class="map">'+(0==k?"":k)+"</span>");d=document.createElement("DIV");d.id=f;d.style.left=e+"px";d.style.top=g+"px";d.className=a;d.zIndex=h;d.innerHTML=l;d.onmouseover=mouseOverAtom;d.onmouseout=mouseOutAtom;d.onmousedown=mouseDownAtom;d.onmouseup=mouseUpAtom;
ws.appendChild(d);an=atoms.length;atoms.push([round2(e,2),round2(g,2),f,a,b,c,m,k,n]);sBtn("btnNmol",0)}
function addBond(a,f,b,h,e,g,l,d,c,m,k){if(!isNewBond(m,k))return!1;void 0==a&&(a="bond");void 0==b&&(b="Bond");void 0==h&&(h=1E3);if(void 0==d||0==d)d=blen;void 0==l&&(l=0);void 0==m&&(m=0);void 0==k&&(k=0);c=document.createElement("DIV");c.className=a;c.style.width=d+"px";c.style.left=e+"px";c.style.top=g+"px";c.style.transform="translate(-4px,-4px) rotate("+l+"deg)";c.id=f;c.zIndex=h;c.onmouseover=mouseOverBond;c.onmouseout=mouseOutBond;c.onmouseup=mouseUpBond;ws.appendChild(c);bn=bonds.length;
if(isNewBond(m,k)){switch(a){case "bond singleBond":addBond2(c,1);bt=1;st=0;break;case "bond doubleBond":addBond2(c,2);bt=2;st=0;break;case "bond tripleBond":addBond2(c,3);bt=3;st=0;break;case "bond upBond":addStereoBond(c,0);st=bt=1;break;case "bond downBond":addStereoBond(c,1),bt=1,st=6}bonds.push([round2(e,2),round2(g,2),round2(l,2),f,a,b,m,k,bt,st]);atoms[m][8]+=bt;atoms[k][8]+=bt;addSymbol(atoms[m][2]);addSymbol(atoms[k][2])}return!0}
function addSymbol(a){document.getElementById(a);a=parseInt(a.split("a")[1]);var f=document.getElementById("s"+a),b=parseInt(atoms[a][6]);parseInt(atoms[a][0]);parseInt(atoms[a][1]);switch(atoms[a][5]){case "H":var h="";switch(atoms[a][8]){default:b="H";atoms[a][6]=0;break;case 2:b="H<sup>+</sup>",atoms[a][6]=1}break;case "C":h="";switch(atoms[a][8]){case 0:switch(b){default:b="CH<sub>4</sub>";atoms[a][6]=0;break;case 1:b="CH<sub>3</sub><sup>+</sup>";atoms[a][6]=1;break;case -1:b="CH<sub>3</sub><sup>-</sup>",
atoms[a][6]=-1}break;case 1:switch(b){default:b="";atoms[a][6]=0;break;case 1:b="CH<sub>2</sub><sup>+</sup>";atoms[a][6]=1;break;case -1:b="CH<sub>2</sub><sup>-</sup>",atoms[a][6]=-1}break;case 2:switch(b){default:b="";atoms[a][6]=0;break;case 1:b="CH<sup>+</sup>";atoms[a][6]=1;break;case -1:b="CH<sup>-</sup>",atoms[a][6]=-1}break;case 3:switch(b){default:b="";atoms[a][6]=0;break;case 1:b="C<sup>+</sup>";atoms[a][6]=1;break;case -1:b="C<sup>-</sup>",atoms[a][6]=-1}break;default:b="";atoms[a][6]=0;
break;case 5:b="C<sup>+</sup>";atoms[a][6]=1;break;case 6:b="C<sup>2+</sup>",atoms[a][6]=2}break;case "N":h="h-blue";switch(atoms[a][8]){case 0:switch(b){default:b="NH<sub>3</sub>";atoms[a][6]=0;break;case 1:b="NH<sub>4</sub><sup>+</sup>";atoms[a][6]=1;break;case -1:b="NH<sub>2</sub><sup>-</sup>",atoms[a][6]=-1}break;case 1:switch(b){default:b="NH<sub>2</sub>";atoms[a][6]=0;break;case 1:b="NH<sup>+</sup>";atoms[a][6]=1;break;case -1:b="NH<sup>-</sup>",atoms[a][6]=-1}break;case 2:switch(b){default:b=
"NH";atoms[a][6]=0;break;case 1:b="N<sup>+</sup>";atoms[a][6]=1;break;case -1:b="N<sup>-</sup>",atoms[a][6]=-1}break;default:atoms[a][6]=0;b="N";break;case 4:b="N<sup>+</sup>";atoms[a][6]=1;break;case 6:b="N<sup>-</sup>",atoms[a][6]=-1}break;case "O":h="h-red";switch(atoms[a][8]){case 0:switch(b){default:b="OH<sub>2</sub>";atoms[a][6]=0;break;case 1:b="OH<sub>3</sub><sup>+</sup>";atoms[a][6]=1;break;case -1:b="OH<sup>-</sup>",atoms[a][6]=-1}break;case 1:switch(b){default:b="OH";atoms[a][6]=0;break;
case 1:b="OH<sub>2</sub><sup>+</sup>";atoms[a][6]=1;break;case -1:b="O<sup>-</sup>",atoms[a][6]=-1}break;default:switch(b){default:b="O";atoms[a][6]=0;break;case 1:b="OH<sup>+</sup>";atoms[a][6]=1;break;case -1:b="O<sup>-</sup>",atoms[a][6]=-1}break;case 3:b="O<sup>+</sup>";atoms[a][6]=1;break;case 4:b="O<sup>2+</sup>";atoms[a][6]=2;break;case 5:b="O<sup>3+</sup>";atoms[a][6]=3;break;case 6:b="O<sup>4+</sup>",atoms[a][6]=4}break;case "S":h="h-sulphur";switch(atoms[a][8]){case 0:switch(b){default:b=
"SH<sub>2</sub>";atoms[a][6]=0;break;case 1:b="SH<sub>3</sub><sup>+</sup>";atoms[a][6]=1;break;case -1:b="SH<sup>-</sup>",atoms[a][6]=-1}break;case 1:switch(b){default:b="SH";atoms[a][6]=0;break;case 1:b="SH<sub>2</sub><sup>+</sup>";atoms[a][6]=1;break;case -1:b="S<sup>-</sup>",atoms[a][6]=-1}break;default:switch(b){default:b="S";atoms[a][6]=0;break;case 1:b="SH<sup>+</sup>";atoms[a][6]=1;break;case -1:b="S<sup>-</sup>",atoms[a][6]=-1}break;case 3:b="S<sup>+</sup>";atoms[a][6]=1;break;case 5:b="SH";
atoms[a][6]=0;break;case 7:b="S<sup>+</sup>";atoms[a][6]=1;break;case 8:b="S<sup>2+</sup>",atoms[a][6]=2}break;case "F":h="h-fluorine";switch(atoms[a][8]){case 0:switch(b){default:b="FH";atoms[a][6]=0;break;case -1:b="F<sup>-</sup>",atoms[a][6]=-1}break;default:b="F";atoms[a][6]=0;break;case 2:b="F<sup>+</sup>",atoms[a][6]=1}break;case "Cl":h="h-chlorine";switch(atoms[a][8]){case 0:switch(b){default:b="ClH";atoms[a][6]=0;break;case -1:b="Cl<sup>-</sup>",atoms[a][6]=-1}break;default:b="Cl";atoms[a][6]=
0;break;case 2:b="Cl<sup>+</sup>",atoms[a][6]=1}break;case "Br":h="h-bromine";switch(atoms[a][8]){case 0:switch(b){default:b="BrH";atoms[a][6]=0;break;case -1:b="Br<sup>-</sup>",atoms[a][6]=-1}break;default:b="Br";atoms[a][6]=0;break;case 2:b="Br<sup>+</sup>",atoms[a][6]=1}break;case "I":h="h-iodine";switch(atoms[a][8]){case 0:switch(b){default:b="IH";atoms[a][6]=0;break;case -1:b="I<sup>-</sup>",atoms[a][6]=-1}break;default:b="I";atoms[a][6]=0;break;case 2:b="I<sup>+</sup>",atoms[a][6]=1}break;case "P":h=
"h-phosphorus";switch(atoms[a][8]){case 0:switch(b){default:b="PH<sub>3</sub>";atoms[a][6]=0;break;case 1:b="PH<sub>4</sub><sup>+</sup>";atoms[a][6]=1;break;case -1:b="PH<sub>2</sub><sup>-</sup>",atoms[a][6]=-1}break;case 1:b="PH<sub>2</sub>";atoms[a][6]=0;break;case 2:b="PH";atoms[a][6]=0;break;default:b="P";atoms[a][6]=0;break;case 4:b="P<sup>+</sup>";atoms[a][6]=1;break;case 6:b="P<sup>-</sup>";atoms[a][6]=-1;break;case 7:b="P<sup>2+</sup>";atoms[a][6]=2;break;case 8:b="P<sup>3+</sup>",atoms[a][6]=
3}break;default:h="",b=atoms[a][5]}f.innerHTML=b;f.className=h}
function addRing(a,f,b,h){void 0==b&&(b=3);void 0==h&&(h=0);var e=360/b;switch(b){case 4:case 8:r0=.5*e;break;default:r0=0}var g=atoms.length,l=bonds.length,d=[];rlen=.5*blen/Math.cos(toRad(.5*(180-e)));for(var c=0;c<b;c++){angle=e*c+r0+h;var m=rlen*Math.sin(toRad(angle));var k=-rlen*Math.cos(toRad(angle));addAtom("atom C","a"+g,"Atom "+(g+1),2E3+g,a+m,f+k);d.push([a+m,f+k]);g++}for(c=0;c<b;c++)j=(c+1)%b,m=d[j][0]-d[c][0],k=d[j][1]-d[c][1],a=toDeg(Math.atan2(k,m)),xstart=0==a?Math.min(d[c][0],d[j][0]):
d[c][0],ystart=d[c][1],addBond("bond singleBond","b"+l,"Bond "+(l+1),1E3+l,xstart,ystart,a),l++}
function addBenzene(a,f,b,h){void 0==b&&(b=6);var e=360/b;switch(b){case 4:case 8:r0=.5*e;break;default:r0=0}var g=atoms.length;h=bonds.length;var l=[];rlen=.5*blen/Math.cos(toRad(.5*(180-e)));for(var d=0;d<b;d++){angle=e*d+r0;var c=rlen*Math.sin(toRad(angle));var m=-rlen*Math.cos(toRad(angle));addAtom("atom C","a"+g,"Atom "+(g+1),2E3+g,a+c,f+m);l.push([a+c,f+m]);g++}for(d=0;d<b;d++){j=(d+1)%b;c=l[j][0]-l[d][0];m=l[j][1]-l[d][1];f=toDeg(Math.atan2(m,c));xstart=0==f?Math.min(l[d][0],l[j][0]):l[d][0];
ystart=l[d][1];switch(d){case 0:case 2:case 4:a="bond doubleBond";break;default:a="bond singleBond"}addBond(a,"b"+h,"Bond "+(h+1),1E3+h,xstart,ystart,f,0,0,l[d][2],l[j][2])&&h++}}
function addChain(a,f,b,h){void 0==b&&(b=2);for(var e,g,l=atoms.length,d=bonds.length,c=[],m=[-30,30,-30,30,-30,30,-30,30,-30,30],k=isNewMolecule(),n=0;n<=b;n++){e=isOnAtom2(a,f);switch(!0){case k:case -1==e:addAtom("atom C","a"+l,"Atom "+(l+1),2E3+l,a,f);c.push([a,f,l]);l++;break;case -1!=e:a=atoms[e][0],f=atoms[e][1],c.push([a,f,e])}angle=m[n]+h;e=blen*Math.cos(toRad(angle));g=blen*Math.sin(toRad(angle));a+=e;f+=g}for(n=0;n<b;n++)j=n+1,e=c[j][0]-c[n][0],g=c[j][1]-c[n][1],a=toDeg(Math.atan2(g,e)),
xstart=0==a?Math.min(c[n][0],c[j][0]):c[n][0],ystart=c[n][1],addBond("bond singleBond","b"+d,"Bond "+(d+1),1E3+d,xstart,ystart,a,0,0,c[n][2],c[j][2])&&d++;distance=0;return!0}
function addIsochain(a,f,b,h){void 0==b&&(b=2);for(var e,g,l=atoms.length,d=bonds.length,c=[],m=[0,-60,60],k=isNewMolecule(),n=0;n<=b+1;n++){e=isOnAtom2(a,f);switch(!0){case k:case -1==e:addAtom("atom C","a"+l,"Atom "+(l+1),2E3+l,a,f);c.push([a,f,l]);l++;break;case -1!=e:a=atoms[e][0],f=atoms[e][1],c.push([a,f,e])}switch(n){case 2:angle=m[n]+h;e=blen*Math.cos(toRad(angle));g=blen*Math.sin(toRad(angle));a=c[1][0]+e;f=c[1][1]+g;break;default:angle=m[n]+h,e=blen*Math.cos(toRad(angle)),g=blen*Math.sin(toRad(angle)),
a+=e,f+=g}}for(n=0;n<=b;n++)switch(n){case 2:n=1;j=3;e=c[j][0]-c[n][0];g=c[j][1]-c[n][1];a=toDeg(Math.atan2(g,e));xstart=0==a?Math.min(c[n][0],c[j][0]):c[n][0];ystart=c[n][1];addBond("bond singleBond","b"+d,"Bond "+(d+1),1E3+d,xstart,ystart,a,0,0,c[n][2],c[j][2])&&d++;n=b+1;break;default:j=n+1,e=c[j][0]-c[n][0],g=c[j][1]-c[n][1],a=toDeg(Math.atan2(g,e)),xstart=0==a?Math.min(c[n][0],c[j][0]):c[n][0],ystart=c[n][1],addBond("bond singleBond","b"+d,"Bond "+(d+1),1E3+d,xstart,ystart,a,0,0,c[n][2],c[j][2])&&
d++}return!0}
function addRing2(a,f,b,h){var e=isNewMolecule(),g=isOnAtom();if(!e&&-1==g&&-1==onBond)return!1;void 0==b&&(b=3);var l=0,d=0,c=atoms.length;e=bonds.length;g=[];var m=[];switch(b){case 3:m=[0,120,-120];break;case 4:m=[0,90,180,-90];break;case 5:m=[0,72,144,-144,-72];break;case 6:m=[0,60,120,180,-120,-60];break;case 7:m=[0,360/7,102.85715,154.28571,-154.28571,-102.85715];break;case 8:m=[0,45,90,135,180,-135,-90,135]}for(var k=0;k<b;k++){a+=l;f+=d;onAtom=isOnAtom2(a,f);switch(!0){case -1==onAtom:addAtom("atom C",
"a"+c,"Atom "+(c+1),2E3+c,a,f);g.push([a,f,c]);c++;break;case -1!=onAtom:a=atoms[onAtom][0],f=atoms[onAtom][1],g.push([a,f,onAtom]),h=1==k?toDeg(Math.atan2(f-y0,a-x0)):h}angle=m[k]+h;l=blen*Math.cos(toRad(angle));d=blen*Math.sin(toRad(angle));x0=a;y0=f}a=g.length;for(k=0;k<a;k++)j=(k+1)%b,l=g[j][0]-g[k][0],d=g[j][1]-g[k][1],f=toDeg(Math.atan2(d,l)),xstart=0==f?Math.min(g[k][0],g[j][0]):g[k][0],ystart=g[k][1],addBond("bond singleBond","b"+e,"Bond "+(e+1),1E3+e,xstart,ystart,f,0,0,g[k][2],g[j][2])&&
e++;return!0}
function addBenzene2(a,f,b,h){var e=isNewMolecule(),g=isOnAtom();if(!e&&-1==g&&-1==onBond)return!1;void 0==b&&(b=6);var l=0,d=0,c=atoms.length;e=bonds.length;g=[];var m=[];switch(b){case 3:m=[0,120,-120];break;case 4:m=[0,90,180,-90];break;case 5:m=[0,72,144,-144,-72];break;case 6:m=[0,60,120,180,-120,-60];break;case 7:m=[0,360/7,102.85715,154.28571,-154.28571,-102.85715];break;case 8:m=[0,45,90,135,180,-135,-90,135]}for(var k=0;k<b;k++){a+=l;f+=d;onAtom=isOnAtom2(a,f);switch(!0){case -1==onAtom:addAtom("atom C",
"a"+c,"Atom "+(c+1),2E3+c,a,f);g.push([a,f,c]);c++;break;case -1!=onAtom:a=atoms[onAtom][0],f=atoms[onAtom][1],g.push([a,f,onAtom]),h=1==k?toDeg(Math.atan2(f-y0,a-x0)):h}angle=m[k]+h;l=blen*Math.cos(toRad(angle));d=blen*Math.sin(toRad(angle));x0=a;y0=f}a=g.length;for(k=0;k<a;k++){j=(k+1)%b;l=g[j][0]-g[k][0];d=g[j][1]-g[k][1];h=toDeg(Math.atan2(d,l));xstart=0==h?Math.min(g[k][0],g[j][0]):g[k][0];ystart=g[k][1];switch(k){case 0:case 2:case 4:f="bond doubleBond";break;default:f="bond singleBond"}addBond(f,
"b"+e,"Bond "+(e+1),1E3+e,xstart,ystart,h,0,0,g[k][2],g[j][2])&&e++}return!0}
function addRing3(a,f,b,h){var e=isNewMolecule(),g=isOnAtom();switch(!0){case -1!=g:a=atoms[g][0];f=atoms[g][1];break;case !e&&-1==onBond:return!1}var l=atoms.length;e=bonds.length;g=[];for(var d=b.length,c,m,k=0;k<d;k++)switch(rlen=Math.sqrt(b[k][0]*b[k][0]+b[k][1]*b[k][1]),angleRad=Math.atan2(b[k][1],b[k][0]),angle=toDeg(angleRad),angle+=h,c=a+rlen*Math.cos(toRad(angle)),m=f+rlen*Math.sin(toRad(angle)),onAtom=isOnAtom2(c,m),!0){case -1==onAtom:addAtom("atom C","a"+l,"Atom "+(l+1),2E3+l,c,m);g.push([c,
m,l]);l++;break;case -1!=onAtom:g.push([atoms[onAtom][0],atoms[onAtom][1],onAtom])}a=g.length;for(k=0;k<a;k++)j=(k+1)%d,f=g[j][0]-g[k][0],b=g[j][1]-g[k][1],f=toDeg(Math.atan2(b,f)),xstart=0==f?Math.min(g[k][0],g[j][0]):g[k][0],ystart=g[k][1],addBond("bond singleBond","b"+e,"Bond "+(e+1),1E3+e,xstart,ystart,f,0,0,g[k][2],g[j][2])&&e++;return!0}
function changeBondType(a,f){var b=parseInt(a.split("b")[1]),h=bonds[b][6],e=bonds[b][7],g=bonds[b][8],l=0,d=0;atoms[h][6]=0;atoms[e][6]=0;switch(f.split(" ")[1]){case "singleBond":l=1;d=0;break;case "upBond":d=l=1;break;case "downBond":l=1;d=6;break;case "doubleBond":l=2;d=0;break;case "tripleBond":l=3,d=0}bonds[b][4]=f;bonds[b][8]=l;bonds[b][9]=d;atoms[h][8]+=l-g;atoms[e][8]+=l-g;addSymbol(atoms[h][2]);addSymbol(atoms[e][2]);return!0}
function addStereoBond(a,f){void 0==f&&(f=0);var b=parseInt(a.style.width),h="";switch(f){default:h=h+('<svg preserveAspectRatio="none" style="width:'+b+'px;height:6px; position:relative; top:-5px;">')+('<path style="fill:#000000;stroke-width:1;stroke:#000000;" d="'+("M0,3 L"+b+",0 V6 Z")+'"></path>')+"</svg>";break;case 1:var e=b/8;h=h+('<svg preserveAspectRatio="none" style="width:'+b+'px;height:6px; position:relative; top:-5px;">')+'<path style="fill:transparent;stroke-width:1;stroke:#000000;" d="'+
("M0,3 H"+e+" M"+2*e+",2 V4 M"+3*e+",2 V4 M"+4*e+",1  V5 M"+5*e+",1 V5 M"+6*e+",0 V6 M"+7*e+",0 V6 M"+8*e+",0 V6");h+='"></path>';h+="</svg>"}a.innerHTML=h;return!0}
function addBond2(a,f){void 0==f&&(f=1);var b=parseInt(a.style.width),h="";switch(f){default:h=h+('<svg preserveAspectRatio="none" style="width:'+b+'px;height:6px; position:relative; top:-5px;">')+'<path class="pBond" d="'+("M0,3 L"+b+",3")+'"></path></svg>';break;case 2:h=h+('<svg preserveAspectRatio="none" style="width:'+b+'px;height:6px; position:relative; top:-5px;">')+'<path class="pBond" d="'+("M0,2 L"+b+",2 M0,4 L"+b+",4")+'"></path></svg>';break;case 3:h=h+('<svg preserveAspectRatio="none" style="width:'+
b+'px;height:6px; position:relative; top:-5px;">')+'<path class="pBond" d="'+("M0,1 L"+b+",1 M0,3 L"+b+",3 M0,5 L"+b+",5")+'"></path></svg>'}a.innerHTML=h;return!0}function addAtom2(a,f){a.innerHTML='<svg preserveAspectRatio="none" style="width:6px;height:6px; position:relative; top:-3px;"><circle style="fill:transparent;stroke-width:.3;stroke:black;" cx="3" cy="3" r=".5"></circle></svg>';return!0}
function addRing21(a,f,b,h){a=isNewMolecule();var e=isOnAtom();if(!a&&-1==e&&-1==onBond)return!1;void 0==b&&(b=3);var g=atoms.length;var l=bonds.length,d=[],c=[];switch(b){case 3:c=[0,-30,90,-150];break;case 4:c=[0,90,180,-90];break;case 5:c=[0,72,144,-144,-72];break;case 6:c=[0,60,120,180,-120,-60];break;case 7:c=[0,360/7,102.85715,154.28571,-154.28571,-102.85715];break;case 8:c=[0,45,90,135,180,-135,-90,135]}da=180/b-90;a=atoms[e][0];f=atoms[e][1];d.push([a,f,e]);for(e=0;1>e;e++){angle=c[e]+h;x0=
a;y0=f;var m=blen*Math.cos(toRad(angle));var k=blen*Math.sin(toRad(angle));a+=m;f+=k;onAtom=isOnAtom2(a,f);switch(!0){case -1==onAtom:addAtom("atom C","a"+g,"Atom "+(g+1),2E3+g,a,f);d.push([a,f,g]);g++;break;case -1!=onAtom:a=atoms[onAtom][0],f=atoms[onAtom][1],d.push([a,f,onAtom]),h=1==e?toDeg(Math.atan2(f-y0,a-x0)):h}}for(e=0;1>e;e++)j=(e+1)%b,j=0==j?1:j,m=d[j][0]-d[e][0],k=d[j][1]-d[e][1],g=toDeg(Math.atan2(k,m)),x1=0==g?Math.min(d[e][0],d[j][0]):d[e][0],y1=d[e][1],a1=d[e][2],a2=d[j][2],addBond("bond singleBond",
"b"+l,"Bond "+(l+1),1E3+l,x1,y1,g,0,0,a1,a2)&&l++;addRing2(a,f,b,h+da);return!0}
function addBenzene21(a,f,b,h){a=isNewMolecule();var e=isOnAtom();if(!a&&-1==e&&-1==onBond)return!1;void 0==b&&(b=6);var g=atoms.length;var l=bonds.length,d=[];da=180/b-90;a=atoms[e][0];f=atoms[e][1];d.push([a,f,e]);angle=h;x0=a;y0=f;e=blen*Math.cos(toRad(angle));var c=blen*Math.sin(toRad(angle));a+=e;f+=c;onAtom=isOnAtom2(a,f);switch(!0){case -1==onAtom:addAtom("atom C","a"+g,"Atom "+(g+1),2E3+g,a,f);d.push([a,f,g]);break;case -1!=onAtom:a=atoms[onAtom][0],f=atoms[onAtom][1],d.push([a,f,onAtom]),
h=1==i?toDeg(Math.atan2(f-y0,a-x0)):h}i=0;j=i+1;e=d[j][0]-d[i][0];c=d[j][1]-d[i][1];g=toDeg(Math.atan2(c,e));x1=0==g?Math.min(d[i][0],d[j][0]):d[i][0];y1=d[i][1];a1=d[i][2];a2=d[j][2];addBond("bond singleBond","b"+l,"Bond "+(l+1),1E3+l,x1,y1,g,0,0,a1,a2);addBenzene2(a,f,b,h+da);return!0};

function nBonds(d){for(var e=bonds.length,f=[],c=0;c<e;c++)switch(!0){case bonds[c][6]==d:case bonds[c][7]==d:f.push([bonds[c]])}return f.length}
function nextAngle(d){var e=document.getElementById("mode").value;if(!inArray(e,"24 25 26 27 28 32 35 36 37 38 39 40 41".split(" ")))return 0;var f=bonds.length,c=[],a=0,b;for(b=0;b<f;b++)switch(!0){case bonds[b][6]==d:case bonds[b][7]==d:c.push([bonds[b]])}f=c.length;switch(f){case 1:a1=c[0][0][6];a2=c[0][0][7];b=c[0][0][8];x1=atoms[a1][0];y1=atoms[a1][1];x2=atoms[a2][0];y2=atoms[a2][1];a=a1==d?toDeg(Math.atan2(y2-y1,x2-x1)):toDeg(Math.atan2(y1-y2,x1-x2));switch(b){case 1:switch(e){case "24":case "25":case "26":case "27":case "28":case "32":a=
(a+120)%360;break;case "35":a=(a+120+30)%360;break;case "36":a=(a+120+15)%360;break;case "37":a=(a+120+6)%360;break;case "38":case "39":a=(a+120)%360;break;case "40":a=(a+120-4)%360;break;case "41":a=(a+120-7)%360}break;case 2:switch(e){case "24":a=(a+120)%360;break;case "25":case "26":a=(a+180)%360;break;case "32":a=(a+120)%360;break;case "35":a=(a+120+30)%360;break;case "36":a=(a+120+15)%360;break;case "37":a=(a+120+6)%360;break;case "38":case "39":a=(a+120)%360;break;case "40":a=(a+120-4)%360;
break;case "41":a=(a+120-7)%360}break;case 3:switch(e){case "24":case "25":case "26":case "32":a=(a+180)%360;break;case "35":a=(a+120+30)%360;break;case "36":a=(a+120+15)%360;break;case "37":a=(a+120+6)%360;break;case "38":case "39":a=(a+120)%360;break;case "40":a=(a+120-4)%360;break;case "41":a=(a+120-7)%360}}break;case 2:a1=c[0][0][6];a2=c[0][0][7];a3=c[1][0][6];a4=c[1][0][7];x1=atoms[a1][0];y1=atoms[a1][1];x2=atoms[a2][0];y2=atoms[a2][1];x3=atoms[a3][0];y3=atoms[a3][1];x4=atoms[a4][0];y4=atoms[a4][1];
bt_1=c[0][0][8];bt_2=c[1][0][8];da_1=a1==d?toDeg(Math.atan2(y2-y1,x2-x1)):toDeg(Math.atan2(y1-y2,x1-x2));da_2=a3==d?toDeg(Math.atan2(y4-y3,x4-x3)):toDeg(Math.atan2(y3-y4,x3-x4));da_1=0>da_1?360+da_1:da_1;da_2=0>da_2?360+da_2:da_2;a=((da_1+da_2)/2+180*(180>Math.abs(da_1-da_2)))%360;switch(e){case "35":switch(!0){case isShift:case isBtnShift:a=(a-30)%360}break;case "36":switch(!0){case isShift:case isBtnShift:a=(a-45)%360}break;case "37":switch(!0){case isShift:case isBtnShift:a=(a-54)%360}break;case "38":case "39":switch(!0){case isShift:case isBtnShift:a=
(a-60)%360}break;case "40":switch(!0){case isShift:case isBtnShift:a=(a-66)%360}break;case "41":switch(!0){case isShift:case isBtnShift:a=(a-67.5)%360}}break;case 3:case 4:case 5:case 6:case 7:case 8:case 9:case 10:case 11:case 12:e=[];for(b=0;b<f;b++)a1=c[b][0][6],a2=c[b][0][7],x1=atoms[a1][0],y1=atoms[a1][1],x2=atoms[a2][0],y2=atoms[a2][1],da_1=a1==d?toDeg(Math.atan2(y2-y1,x2-x1)):toDeg(Math.atan2(y1-y2,x1-x2)),da_1=0>da_1?360+da_1:da_1,da_1=round2(da_1,0),e.push([da_1]);e.sort(Asc);d=[30,150,270,
330,90,210,0,120,240,300,60,180];c=d.length;for(b=0;b<c;b++)inArrayRange(d[b],15,e)||(a=d[b],b=c)}b=[];b[0]=a;b[1]=f;return b};

function selMol(b){var c=bonds.length,a=[b];b=1;do{var d=a.length;jmin=d-b;jmax=d;for(var f=jmin;f<jmax;f++){b=a[f];for(var e=0;e<c;e++){var g=bonds[e][6];var h=bonds[e][7];switch(!0){case g==b&&!inArray(h,a):a.push([h]);break;case h==b&&!inArray(g,a):a.push([g])}}}b=a.length;b-=d}while(0<b);return a}function lastNumber_(){for(var b=atoms.length,c=[],a=0;a<b;a++)c.push([atoms[a][7]]);c.sort(Desc);return c[0]}
function lastNumber(b){b=selMol(b);for(var c=b.length,a=[],d=0;d<c;d++)a.push([atoms[b[d]][7]]);a.sort(Desc);return a[0]}function addNumber(b,c){var a=document.getElementById(b),d=parseInt(b.split("a")[1]),f=a.getElementsByClassName("map"),e=f.length;switch(!0){case 0==e&&0<c:a.innerHTML+='<span class="map" id="m'+d+'">'+c+"</span>";break;case 1==e&&0<c:f[0].innerHTML=c;break;case 1==e&&0==c:f[0].innerHTML=""}};

function getMol(d,c){void 0==d&&(d=0);void 0==c&&(c=0);var h="mol",e=atoms.length,m=bonds.length,k="",g=0,l=0;var q=("          "+(0).toFixed(4)).slice(-10);switch(c){default:for(var f=[],b=[],n=1.4/blen,a=0;a<e;a++)f.push([atoms[a][0]]),b.push([atoms[a][1]]);f.sort(Asc);b.sort(Asc);f=(round2(parseFloat(f[0]),0)+round2(parseFloat(f[e-1]),0))/2;var r=(round2(parseFloat(b[0]),0)+round2(parseFloat(b[e-1]),0))/2;break;case 1:h="wsCode"}b="MDL Molfile\n  FlameJS201712\n\n"+(String("   "+e).slice(-3)+String("   "+
m).slice(-3)+"  0  0  0  0  0  0  0  0999 V2000\n");for(a=0;a<e;a++){var t=a+1;switch(c){case 0:g=(atoms[a][0]-f)*n;l=(r-atoms[a][1])*n;break;case 1:g=atoms[a][0],l=atoms[a][1]}var u=atoms[a][5];var p=atoms[a][6];var v=atoms[a][7];b+=("          "+g.toFixed(4)).slice(-10)+("          "+l.toFixed(4)).slice(-10)+q+(" "+u+" ").slice(0,3);b+="  0  0  0  0  0  0  0  0  0";b+=("   "+v).slice(-3);b+="  0  0";b+="\n";0!=p&&(k+="M  CHG  1",k+=("    "+t).slice(-4)+("    "+p).slice(-4),k+="\n")}for(a=0;a<m;a++)e=
bonds[a][6]+1,g=bonds[a][7]+1,bt=bonds[a][8],st=bonds[a][9],b+=("   "+e).slice(-3)+("   "+g).slice(-3)+("   "+bt).slice(-3)+("   "+st).slice(-3),b+="  0  0  0",b+="\n";b=b+k+"M  END\n";switch(d){default:document.getElementById(h).value=b;case 1:}return b}
function histAdd(){0==hmol.length&&hmol.push(["MDL Molfile\n  FlameJS\n\n  0  0  0  0  0  0  0  0  0  0999 V2000\nM  END\n",!1]);var d=getMol(1,1),c=hmol.length,h="active"==document.getElementById("btnReac").className.split(" ")[1];switch(!0){case 31<=c:hmol.shift()}hmol.push([d,h]);hcount=hmol.length-1;btnUndo.disabled=0<hcount?!1:!0;btnRedo.disabled=hcount<hmol.length-1?!1:!0}
function histUndo(){var d=0<hcount?hcount-1:hcount,c=document.getElementById("btnReac");d!=hcount&&(hcount=d,setMol(hmol[hcount][0],1),hmol[hcount][1]?(sBtn(c.id,1),on2("imgArrow")):(sBtn(c.id,0),off2("imgArrow")));showTooltip("Undo: "+hcount+" out of "+(hmol.length-1));btnUndo.disabled=0<hcount?!1:!0;btnRedo.disabled=hcount<hmol.length-1?!1:!0}
function histRedo(){var d=hcount<hmol.length-1?hcount+1:hcount,c=document.getElementById("btnReac");d!=hcount&&(hcount=d,setMol(hmol[hcount][0],1),hmol[hcount][1]?(sBtn(c.id,1),on2("imgArrow")):(sBtn(c.id,0),off2("imgArrow")));showTooltip("Redo: "+hcount+" out of "+(hmol.length-1));btnUndo.disabled=0<hcount?!1:!0;btnRedo.disabled=hcount<hmol.length-1?!1:!0};

function setMol(u,p){void 0==p&&(p=0);var f="mol";switch(p){case 1:f="wsCode"}var c=document.getElementById(f);void 0!=u&&(c.value=u);var d=c.value.split("\n");c=[];var g=[],k=[];if(d[3]){var h=d[3].substr(0,3);h=parseInt(h);var m=d[3].substr(3,3);m=parseInt(m);var a="V2000"==d[3].substr(34,5)}switch(!0){case !a:return showTooltip("Not an MDL Molfile!"),!1;case 0==h:return showTooltip("Empty MDL Molfile!"),clearWorkspace(),!1}for(a=0;a<h;a++){c.push([0,0,0,"",0,0]);var e=d[a+4].substr(0,10);c[a][0]=
Number(e);var q=d[a+4].substr(10,10);c[a][1]=Number(q);var b=d[a+4].substr(20,10);c[a][2]=Number(b);var r=d[a+4].substr(30,3);c[a][3]=r.trim();b=d[a+4].substr(36,3);b=Number(b);switch(b){case 1:b=3;break;case 2:b=2;break;case 3:b=1;break;case 4:b=".";break;case 5:b=-1;break;case 6:b=-2;break;case 7:b=-3;break;default:b="0"}c[a][4]=b;var n=d[a+4].substr(60,3);n=Number(n);c[a][5]=n}for(a=0;a<m;a++){g.push([0,0,0,0]);b=d[a+4+h].substr(0,3);g[a][0]=Number(b);e=d[a+4+h].substr(3,3);g[a][1]=Number(e);f=
d[a+4+h].substr(6,3);g[a][2]=Number(f);var l=d[a+4+h].substr(9,3);g[a][3]=Number(l)}for(a=4+h+m;"M  END"!=d[a].substr(0,6);){switch(d[a].substr(0,6)){case "M  CHG":for(e=d[a].substr(6,3),e=Number(e),j=0;j<e;j++)f=d[a].substr(9+8*j,4),f=Number(f),b=d[a].substr(13+8*j,4),b=Number(b),k.push([f,b]),c[f-1][4]=b}a++}switch(p){default:d=blen/1.4;if(0<g.length){a=0;k=g.length;f=0;do{b=g[a][0];e=g[a][1];x1=c[b-1][0];x2=c[e-1][0];y1=c[b-1][1];y2=c[e-1][1];e1=c[b-1][3];e2=c[e-1][3];switch(!0){case "C"==e1&&
"C"==e2:f=Math.sqrt((x2-x1)*(x2-x1)+(y2-y1)*(y2-y1))}a++}while(0==f&&a<k);if(0==f){a=0;do{b=g[a][0];e=g[a][1];x1=c[b-1][0];x2=c[e-1][0];y1=c[b-1][1];y2=c[e-1][1];e1=c[b-1][3];e2=c[e-1][3];switch(!0){case "H"!=e1&&"H"!=e2:f=Math.sqrt((x2-x1)*(x2-x1)+(y2-y1)*(y2-y1))}a++}while(0==f&&a<k)}if(0==f){a=0;do b=g[a][0],e=g[a][1],x1=c[b-1][0],x2=c[e-1][0],y1=c[b-1][1],y2=c[e-1][1],e1=c[b-1][3],e2=c[e-1][3],f=Math.sqrt((x2-x1)*(x2-x1)+(y2-y1)*(y2-y1)),a++;while(0==f&&a<k)}switch(!0){case 1.4!=round2(f,3):showTooltip("Bond length: "+
round2(f,2)),d=blen/f}}k=[];e=[];b=[];for(a=0;a<h;a++)k.push([c[a][0]]),e.push([c[a][1]]),b.push([c[a][2]]);k.sort(Asc);e.sort(Asc);b.sort(Asc);k=(round2(parseFloat(k[0]),4)+round2(parseFloat(k[h-1]),4))/2;e=(round2(parseFloat(e[0]),4)+round2(parseFloat(e[h-1]),4))/2;round2(parseFloat(b[0]),4);round2(parseFloat(b[h-1]),4);b=ws.offsetWidth/2;f=ws.offsetHeight/2;for(a=0;a<h;a++)c[a][0]=round2(b+(c[a][0]-k)*d,0),c[a][1]=round2(f-(c[a][1]-e)*d,0);case 1:}clearWorkspace();d="";for(a=k=0;a<h;a++){d="atom "+
c[a][3];f="a"+a;l="Atom "+(a+1);var t=2E3+a;e=c[a][0];q=c[a][1];k=0;r=c[a][3];b=c[a][4];n=c[a][5];addAtom(d,f,l,t,e,q,0,0,r,b,n,0);addSymbol(f)}for(a=0;a<m;a++){b=g[a][0];e=g[a][1];f=g[a][2];l=g[a][3];switch(l){default:switch(f){case 1:d="singleBond";break;case 2:d="doubleBond";break;case 3:d="tripleBond"}break;case 1:d="upBond";break;case 6:d="downBond"}d="bond "+d;f="b"+a;l="bond "+(a+1);t=1E3+a;x1=c[b-1][0];y1=c[b-1][1];x2=c[e-1][0];y2=c[e-1][1];deg=toDeg(Math.atan2(y2-y1,x2-x1));h=Math.ceil(Math.sqrt((x2-
x1)*(x2-x1)+(y2-y1)*(y2-y1)));addBond(d,f,l,t,x1,y1,deg,h,k,b-1,e-1);addSymbol("a"+(b-1));addSymbol("a"+(e-1))}return!0};

function getRxn(){var b="$RXN\n\n  FlameJS201712\n\n";var k=0,f=0,d=atoms.length;mo=[];moa=[];mob=[];for(var l=[],e=[],g=[],a=0,h=-1;a<d;){if(!inArray(a,l))for(h++,mo=selectMol2(a),0<mo[0].length&&(moa.push([mo[0]]),mob.push([mo[1]])),j=0;j<mo[0].length;j++)l.push([mo[0][j]]);a++}d=parseInt(ws.offsetWidth)/2;parseInt(ws.offsetHeight);for(a=0;a<moa.length;a++){for(j=x0=0;j<moa[a][0].length;j++)x0+=atoms[moa[a][0][j]][0];x0/=moa[a][0].length;switch(!0){case x0<=d:k++;e.push([a]);break;case x0>d:f++,
g.push([a])}}b+=String("   "+k).slice(-3)+String("   "+f).slice(-3)+"\n";for(a=0;a<k;a++)b+="$MOL\n",b+="  MDL Molfile\n",b+="  REAGENT#"+(a+1)+"\n",b+="\n",b+=getMol2(moa[e[a]][0],mob[e[a]][0]);for(a=0;a<f;a++)b+="$MOL\n",b+="  MDL Molfile\n",b+="  PRODUCT#"+(a+1)+"\n",b+="\n",b+=getMol2(moa[g[a]][0],mob[g[a]][0]);document.getElementById("mol").value=b}
function getMol2(b,k){var f=b.length,d=k.length,l="";var e=("          "+(0).toFixed(4)).slice(-10);for(var g=[],a=[],h=1.4/blen,c=0;c<f;c++)g.push([atoms[b[c]][0]]),a.push([atoms[b[c]][1]]);g.sort(Asc);a.sort(Asc);var p=(round2(parseFloat(g[0]),0)+round2(parseFloat(g[f-1]),0))/2,q=(round2(parseFloat(a[0]),0)+round2(parseFloat(a[f-1]),0))/2;a=""+(String("   "+f).slice(-3)+String("   "+d).slice(-3)+"  0  0  0  0  0  0  0  0999 V2000\n");g=[];for(c=0;c<f;c++){a0=parseInt(b[c]);var m=c+1;g.push([a0,
m]);var r=(atoms[b[c]][0]-p)*h;var t=(q-atoms[b[c]][1])*h;var u=atoms[b[c]][5];var n=atoms[b[c]][6];var v=atoms[b[c]][7];a+=("          "+r.toFixed(4)).slice(-10)+("          "+t.toFixed(4)).slice(-10)+e+(" "+u+" ").slice(0,3);a+="  0  0  0  0  0  0  0  0  0";a+=String("   "+v).slice(-3);a+="  0  0";a+="\n";0!=n&&(l+="M  CHG  1",l+=("    "+m).slice(-4)+("    "+n).slice(-4),l+="\n")}for(c=0;c<d;c++)f=reOrder(bonds[k[c]][6],g),e=reOrder(bonds[k[c]][7],g),bt=bonds[k[c]][8],st=bonds[k[c]][9],a+=("   "+
f).slice(-3)+("   "+e).slice(-3)+("   "+bt).slice(-3)+("   "+st).slice(-3),a+="  0  0  0",a+="\n";return a+l+"M  END\n"}function reOrder(b,k){for(var f=k.length,d=0;d<f;d++)if(b==k[d][0]){var l=k[d][1];d=f}return l}
function selectMol2(b,k){var f=bonds.length,d=[b],l=[];var e=1;do{var g=d.length;jmin=g-e;jmax=g;for(var a=jmin;a<jmax;a++){b=d[a];for(var h=0;h<f;h++){e=bonds[h][6];var c=bonds[h][7];switch(!0){case e==b&&!inArray(c,d):d.push([c]);break;case c==b&&!inArray(e,d):d.push([e])}}}e=d.length;e-=g}while(0<e);d.sort(Asc);for(h=0;h<f;h++)switch(e=bonds[h][6],c=bonds[h][7],!0){case inArray(e,d):case inArray(c,d):l.push([h])}return[d,l]};

function setRxn(b){void 0==b&&(b="mol");mols=document.getElementById(b).value.split("$MOL\n");b=mols[0].split("\n");if("$RXN"!=b[0].trim())return showTooltip("Not a RXN file."),!1;b[2].trim();if(b[4]){var h=parseInt(b[4].substr(0,3)),g=parseInt(b[4].substr(3,3));sBtn("btnReac",1);on2("imgArrow")}clearWorkspace();document.getElementById("wsCode");for(var m=b=0,k,c=1;c<=h;){switch(h){case 1:mPos=2;break;case 2:mPos=2*(c-1)+1;break;default:mPos=c}k=setMol2(mols[c],0,mPos,b,m);c++;b+=k[0];m+=k[1]}for(c=
1;c<=g;){switch(g){case 1:mPos=6;break;case 2:mPos=2*(c-1)+5;break;default:mPos=4+c}k=setMol2(mols[h+c],0,mPos,b,m);c++;b+=k[0];m+=k[1]}switch(!0){case 0<h&&0==g:for(c=1;c<=h;){switch(h){case 1:mPos=6;break;case 2:mPos=2*(c-1)+5;break;default:mPos=4+c}k=setMol2(mols[c],0,mPos,b,m);c++;b+=k[0];m+=k[1]}break;case 0==h&&0<g:for(h=g,c=1;c<=g;){switch(h){case 1:mPos=2;break;case 2:mPos=2*(c-1)+1;break;default:mPos=c}k=setMol2(mols[c],0,mPos,b,m);c++;b+=k[0];m+=k[1]}}}
function setMol2(b,h,g,m,k){void 0==h&&(h=0);void 0==g&&(g=1);void 0==m&&(m=0);void 0==k&&(k=0);var c=b.split("\n");b=[];var l=[],f=[];if(c[3]){var n=c[3].substr(0,3);n=parseInt(n);var r=c[3].substr(3,3);r=parseInt(r);var a="V2000"==c[3].substr(34,5)}switch(!0){case !a:return showTooltip("Not an MDL Molfile!"),!1;case 0==n:return showTooltip("Empty MDL Molfile!"),!1}for(a=0;a<n;a++){b.push([0,0,0,"",0,0]);var e=c[a+4].substr(0,10);b[a][0]=Number(e);var p=c[a+4].substr(10,10);b[a][1]=Number(p);var d=
c[a+4].substr(20,10);b[a][2]=Number(d);var q=c[a+4].substr(30,3);b[a][3]=q.trim();d=c[a+4].substr(36,3);d=Number(d);switch(d){case 1:d=3;break;case 2:d=2;break;case 3:d=1;break;case 4:d=".";break;case 5:d=-1;break;case 6:d=-2;break;case 7:d=-3;break;default:d="0"}b[a][4]=d;var t=c[a+4].substr(60,3);t=Number(t);b[a][5]=t}for(a=0;a<r;a++)l.push([0,0,0,0]),d=c[a+4+n].substr(0,3),l[a][0]=Number(d),e=c[a+4+n].substr(3,3),l[a][1]=Number(e),p=c[a+4+n].substr(6,3),l[a][2]=Number(p),q=c[a+4+n].substr(9,3),
l[a][3]=Number(q);for(a=4+n+r;"M  END"!=c[a].substr(0,6);){switch(c[a].substr(0,6)){case "M  CHG":for(e=c[a].substr(6,3),e=Number(e),j=0;j<e;j++)p=c[a].substr(9+8*j,4),p=Number(p),d=c[a].substr(13+8*j,4),d=Number(d),f.push([p,d]),b[p-1][4]=d}a++}switch(h){default:h=blen/1.4;if(0<l.length){a=0;c=l.length;f=0;do{d=l[a][0];e=l[a][1];x1=b[d-1][0];x2=b[e-1][0];y1=b[d-1][1];y2=b[e-1][1];e1=b[d-1][3];e2=b[e-1][3];switch(!0){case "C"==e1&&"C"==e2:f=Math.sqrt((x2-x1)*(x2-x1)+(y2-y1)*(y2-y1))}a++}while(0==
f&&a<c);if(0==f){a=0;do{d=l[a][0];e=l[a][1];x1=b[d-1][0];x2=b[e-1][0];y1=b[d-1][1];y2=b[e-1][1];e1=b[d-1][3];e2=b[e-1][3];switch(!0){case "H"!=e1&&"H"!=e2:f=Math.sqrt((x2-x1)*(x2-x1)+(y2-y1)*(y2-y1))}a++}while(0==f&&a<c)}if(0==f){a=0;do d=l[a][0],e=l[a][1],x1=b[d-1][0],x2=b[e-1][0],y1=b[d-1][1],y2=b[e-1][1],e1=b[d-1][3],e2=b[e-1][3],f=Math.sqrt((x2-x1)*(x2-x1)+(y2-y1)*(y2-y1)),a++;while(0==f&&a<c)}switch(!0){case 1.4!=round2(f,3):showTooltip("Bond length: "+round2(f,2)),h=blen/f}}c=[];d=[];f=[];for(a=
0;a<n;a++)c.push([b[a][0]]),d.push([b[a][1]]),f.push([b[a][2]]);c.sort(Asc);d.sort(Asc);f.sort(Asc);c=(round2(parseFloat(c[0]),4)+round2(parseFloat(c[n-1]),4))/2;d=(round2(parseFloat(d[0]),4)+round2(parseFloat(d[n-1]),4))/2;round2(parseFloat(f[0]),4);round2(parseFloat(f[n-1]),4);g*=ws.offsetWidth/8;f=ws.offsetHeight/2;for(a=0;a<n;a++)b[a][0]=round2(g+(b[a][0]-c)*h,0),b[a][1]=round2(f-(b[a][1]-d)*h,0);case 1:}g="";for(a=h=0;a<n;a++){g="atom "+b[a][3];c="a"+(a+m);f="Atom "+(a+1+m);var u=2E3+(a+m);e=
b[a][0];p=b[a][1];h=0;q=b[a][3];d=b[a][4];t=b[a][5];addAtom(g,c,f,u,e,p,0,0,q,d,t,0);addSymbol(c)}for(a=0;a<r;a++){d=l[a][0];e=l[a][1];p=l[a][2];q=l[a][3];switch(q){default:switch(p){case 1:g="singleBond";break;case 2:g="doubleBond";break;case 3:g="tripleBond"}break;case 1:g="upBond";break;case 6:g="downBond"}g="bond "+g;c="b"+(a+k);f="bond "+(a+1+k);u=1E3+a;x1=b[d-1][0];y1=b[d-1][1];x2=b[e-1][0];y2=b[e-1][1];deg=toDeg(Math.atan2(y2-y1,x2-x1));p=Math.ceil(Math.sqrt((x2-x1)*(x2-x1)+(y2-y1)*(y2-y1)));
addBond(g,c,f,u,x1,y1,deg,p,h,d-1+m,e-1+m);addSymbol("a"+(d-1));addSymbol("a"+(e-1))}return[n,r]};

function showCode(b){void 0==b&&(b="mol");document.getElementById(b).value=ws.innerHTML}function showMolInfo(b){var d=document.getElementById("mol");void 0==b&&(b=0);switch(b){case 0:d.value=atoms;break;case 1:d.value=bonds}}function showSmiles(){for(var b=document.getElementById("mol"),d=atoms.length,a,c="",e=0;e<d;e++){j=(e+1)%d;a=getBondType(e,j);switch(a[0][0]){case 1:a="";break;case 2:a="=";break;case 3:a=":";break;default:a="-"}c+=atoms[e][5]+a}b.value=c}
function getBondType(b,d){for(var a=bonds.length,c="",e=[],f=0;f<a;f++)switch(!0){case bonds[f][6]==b&&bonds[f][7]==d:case bonds[f][6]==d&&bonds[f][7]==b:c=bonds[f][4].split(" ")[1],f=a}switch(c){case "singleBond":a=1;c=0;break;case "doubleBond":a=2;c=0;break;case "tripleBond":a=3;c=0;break;case "upBond":c=a=1;break;case "downBond":a=1;c=6;break;default:a=1,c=0}e.push([a,c]);return e};

